/* Generated by JSIL v0.8.2 build 30533. See http://jsil.org/ for more information. */ 
'use strict';
var $asm00 = JSIL.DeclareAssembly("ExaPhaser.SharpJS.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null");

JSIL.DeclareNamespace("JSIL");
/* class JSIL.RequiresJSILRuntimeException */ 

(function RequiresJSILRuntimeException$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.Exception)) ();
  };


  function RequiresJSILRuntimeException__ctor () {
    $T00().prototype._ctor.call(this, "This method is a stub! It must be run in the JSIL runtime.");
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.Exception"), 
      Name: "JSIL.RequiresJSILRuntimeException", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      RequiresJSILRuntimeException__ctor
    );

    $.ImplementInterfaces(
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

