/* Generated by JSIL v0.8.2 build 30533. See http://jsil.org/ for more information. */ 
'use strict';
var $asm03 = JSIL.DeclareAssembly("SharpJS.Dom, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null");

JSIL.DeclareNamespace("SharpJS");
JSIL.DeclareNamespace("SharpJS.Dom");
/* class SharpJS.Dom.Document */ 

(function Document$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm02.System.Int32)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm07.System.Linq.Enumerable)) ();
  };
  var $T04 = function () {
    return ($T04 = JSIL.Memoize($asm02.System.Object)) ();
  };
  var $T05 = function () {
    return ($T05 = JSIL.Memoize($asm02.System.Collections.Generic.IEnumerable$b1.Of($asm02.System.Object))) ();
  };
  var $T06 = function () {
    return ($T06 = JSIL.Memoize(System.Array.Of($asm02.System.Object))) ();
  };
  var $T07 = function () {
    return ($T07 = JSIL.Memoize($asm02.System.Func$b2.Of($asm02.System.Object, $asm03.SharpJS.Dom.Element))) ();
  };
  var $T08 = function () {
    return ($T08 = JSIL.Memoize($asm02.System.Type)) ();
  };
  var $T09 = function () {
    return ($T09 = JSIL.Memoize($asm02.System.Activator)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(new JSIL.ConstructorSignature($asm03.SharpJS.Dom.Element, [$asm02.System.String]))) ();
  };
  var $S01 = function () {
    return ($S01 = JSIL.Memoize(new JSIL.MethodSignature($asm02.TypeRef("System.Collections.Generic.IEnumerable`1", ["!!1"]), [$asm02.TypeRef("System.Collections.Generic.IEnumerable`1", ["!!0"]), $asm02.TypeRef("System.Func`2", ["!!0", "!!1"])], ["TSource", "TResult"]))) ();
  };
  var $S02 = function () {
    return ($S02 = JSIL.Memoize(new JSIL.MethodSignature($asm03.SharpJS.Dom.Element, [$asm02.System.Object]))) ();
  };


  function Document__ctor () {
  }; 

  function Document_CreateElement (elementNodeName) {
    return $S00().Construct(elementNodeName);
  }; 

  function Document_get_Body () {
    return $thisType.GetElementsByTagName("body")[0];
  }; 

  function Document_get_ClientHeight () {
    return $T02().$Cast(document.documentElement.clientHeight);
  }; 

  function Document_get_ClientWidth () {
    return $T02().$Cast(document.documentElement.clientWidth);
  }; 

  function Document_get_Title () {
    return $T00().$Cast(document.title);
  }; 

  function Document_GetElementById (id) {
    return $T01().GetById(id);
  }; 

  function Document_GetElementsByClassName (tagName) {
    return $T03().ToArray$b1($T01())($S01().CallStatic($T03(), "Select$b2", [$asm02.System.Object, $asm03.SharpJS.Dom.Element], $T05().$Cast($T06().$Cast(Array.prototype.slice.call(document.getElementsByClassName(tagName)))), $T07().New(null, null, new JSIL.MethodPointerInfo($asm03.SharpJS.Dom.Element, "GetElement", $S02(), true, false))));
  }; 

  function Document_GetElementsByTag$b1 (T) {
    $T09().CreateInstance$b1(T)();
    return $T03().ToArray$b1($T01())($S01().CallStatic($T03(), "Select$b2", [$asm02.System.Object, $asm03.SharpJS.Dom.Element], $T05().$Cast($T06().$Cast(Array.prototype.slice.call(document.getElementsByTagName(elementInstance.TagName)))), $T07().New(null, null, new JSIL.MethodPointerInfo($asm03.SharpJS.Dom.Element, "GetElement", $S02(), true, false))));
  }; 

  function Document_GetElementsByTagName (tagName) {
    return $T03().ToArray$b1($T01())($S01().CallStatic($T03(), "Select$b2", [$asm02.System.Object, $asm03.SharpJS.Dom.Element], $T05().$Cast($T06().$Cast(Array.prototype.slice.call(document.getElementsByTagName(tagName)))), $T07().New(null, null, new JSIL.MethodPointerInfo($asm03.SharpJS.Dom.Element, "GetElement", $S02(), true, false))));
  }; 

  function Document_set_Title (value) {
    document.title = value;
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.Object"), 
      Name: "SharpJS.Dom.Document", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      Document__ctor
    );

    $.Method({Static:true , Public:true }, "CreateElement", 
      new JSIL.MethodSignature($asm03.TypeRef("SharpJS.Dom.Element"), [$.String]), 
      Document_CreateElement
    );

    $.Method({Static:true , Public:true }, "get_Body", 
      JSIL.MethodSignature.Return($asm03.TypeRef("SharpJS.Dom.Element")), 
      Document_get_Body
    );

    $.Method({Static:true , Public:true }, "get_ClientHeight", 
      JSIL.MethodSignature.Return($.Int32), 
      Document_get_ClientHeight
    );

    $.Method({Static:true , Public:true }, "get_ClientWidth", 
      JSIL.MethodSignature.Return($.Int32), 
      Document_get_ClientWidth
    );

    $.Method({Static:true , Public:true }, "get_Title", 
      JSIL.MethodSignature.Return($.String), 
      Document_get_Title
    );

    $.Method({Static:true , Public:true }, "GetElementById", 
      new JSIL.MethodSignature($asm03.TypeRef("SharpJS.Dom.Element"), [$.String]), 
      Document_GetElementById
    );

    $.Method({Static:true , Public:true }, "GetElementsByClassName", 
      new JSIL.MethodSignature($jsilcore.TypeRef("System.Array", [$asm03.TypeRef("SharpJS.Dom.Element")]), [$.String]), 
      Document_GetElementsByClassName
    );

    $.Method({Static:true , Public:true }, "GetElementsByTag", 
      new JSIL.MethodSignature($jsilcore.TypeRef("System.Array", [$asm03.TypeRef("SharpJS.Dom.Element")]), null, ["T"]), 
      Document_GetElementsByTag$b1
    );

    $.Method({Static:true , Public:true }, "GetElementsByTagName", 
      new JSIL.MethodSignature($jsilcore.TypeRef("System.Array", [$asm03.TypeRef("SharpJS.Dom.Element")]), [$.String]), 
      Document_GetElementsByTagName
    );

    $.Method({Static:true , Public:true }, "set_Title", 
      JSIL.MethodSignature.Action($.String), 
      Document_set_Title
    );

    $.Property({Static:true , Public:true }, "Body", $asm03.TypeRef("SharpJS.Dom.Element"));

    $.Property({Static:true , Public:true }, "Title", $.String);

    $.Property({Static:true , Public:true }, "ClientWidth", $.Int32);

    $.Property({Static:true , Public:true }, "ClientHeight", $.Int32);


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.Element */ 

(function Element$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm02.System.Object)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm02.System.Collections.Generic.Dictionary$b2.Of($asm02.System.Object, $asm03.SharpJS.Dom.Element_Proxy))) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm02.System.ArgumentNullException)) ();
  };
  var $T04 = function () {
    return ($T04 = JSIL.Memoize($asm03.SharpJS.Dom.StyleCollection)) ();
  };
  var $T05 = function () {
    return ($T05 = JSIL.Memoize($asm02.System.EventArgs)) ();
  };
  var $T06 = function () {
    return ($T06 = JSIL.Memoize($asm02.System.EventHandler)) ();
  };
  var $T07 = function () {
    return ($T07 = JSIL.Memoize($asm02.System.Delegate)) ();
  };
  var $T08 = function () {
    return ($T08 = JSIL.Memoize($asm02.System.Threading.Interlocked)) ();
  };
  var $T09 = function () {
    return ($T09 = JSIL.Memoize($asm02.System.Action$b1.Of($asm02.System.Object))) ();
  };
  var $T0A = function () {
    return ($T0A = JSIL.Memoize($asm03.SharpJS.Dom.Element_Proxy)) ();
  };
  var $T0B = function () {
    return ($T0B = JSIL.Memoize($asm02.System.Action$b1)) ();
  };
  var $T0C = function () {
    return ($T0C = JSIL.Memoize($asm02.System.Func$b2.Of($asm02.System.Object, $asm03.SharpJS.Dom.Element))) ();
  };
  var $T0D = function () {
    return ($T0D = JSIL.Memoize($asm02.System.Collections.Generic.IEnumerable$b1.Of($asm02.System.Object))) ();
  };
  var $T0E = function () {
    return ($T0E = JSIL.Memoize(System.Array.Of($asm02.System.Object))) ();
  };
  var $T0F = function () {
    return ($T0F = JSIL.Memoize($asm03.SharpJS.Dom.Element_$l$gc)) ();
  };
  var $T10 = function () {
    return ($T10 = JSIL.Memoize($asm07.System.Linq.Enumerable)) ();
  };
  var $T11 = function () {
    return ($T11 = JSIL.Memoize($asm02.System.Boolean)) ();
  };
  var $T12 = function () {
    return ($T12 = JSIL.Memoize($asm02.System.Double)) ();
  };
  var $T13 = function () {
    return ($T13 = JSIL.Memoize($asm02.System.ArgumentOutOfRangeException)) ();
  };
  var $T14 = function () {
    return ($T14 = JSIL.Memoize($asm02.System.Type)) ();
  };
  var $T15 = function () {
    return ($T15 = JSIL.Memoize($asm02.System.Activator)) ();
  };
  var $T16 = function () {
    return ($T16 = JSIL.Memoize($asm03.SharpJS.Dom.Element_$l$gc__DisplayClass97_0)) ();
  };
  var $T17 = function () {
    return ($T17 = JSIL.Memoize($asm02.System.Collections.Generic.IEnumerable$b1.Of($asm02.System.String))) ();
  };
  var $T18 = function () {
    return ($T18 = JSIL.Memoize($asm02.System.Char)) ();
  };
  var $T19 = function () {
    return ($T19 = JSIL.Memoize(System.Array.Of($asm02.System.Char))) ();
  };
  var $T1A = function () {
    return ($T1A = JSIL.Memoize($asm02.System.Func$b2.Of($asm02.System.String, $asm02.System.Boolean))) ();
  };
  var $T1B = function () {
    return ($T1B = JSIL.Memoize($asm02.System.Collections.Generic.IEnumerator$b1.Of($asm02.System.String))) ();
  };
  var $T1C = function () {
    return ($T1C = JSIL.Memoize($asm02.System.Collections.IEnumerator)) ();
  };
  var $T1D = function () {
    return ($T1D = JSIL.Memoize($asm02.System.IDisposable)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.Object")))) ();
  };
  var $S01 = function () {
    return ($S01 = JSIL.Memoize(new JSIL.ConstructorSignature($asm02.System.Collections.Generic.Dictionary$b2.Of($asm02.System.Object, $asm03.SharpJS.Dom.Element_Proxy), null))) ();
  };
  var $S02 = function () {
    return ($S02 = JSIL.Memoize(new JSIL.ConstructorSignature($asm02.System.ArgumentNullException, [$asm02.System.String]))) ();
  };
  var $S03 = function () {
    return ($S03 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.Object")))) ();
  };
  var $S04 = function () {
    return ($S04 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.Object")))) ();
  };
  var $S05 = function () {
    return ($S05 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.Object")))) ();
  };
  var $S06 = function () {
    return ($S06 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.Object")))) ();
  };
  var $S07 = function () {
    return ($S07 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.Object")))) ();
  };
  var $S08 = function () {
    return ($S08 = JSIL.Memoize(new JSIL.MethodSignature($asm03.SharpJS.Dom.Element, [$asm02.System.Object]))) ();
  };
  var $S09 = function () {
    return ($S09 = JSIL.Memoize(new JSIL.MethodSignature($asm02.TypeRef("System.Collections.Generic.IEnumerable`1", ["!!1"]), [$asm02.TypeRef("System.Collections.Generic.IEnumerable`1", ["!!0"]), $asm02.TypeRef("System.Func`2", ["!!0", "!!1"])], ["TSource", "TResult"]))) ();
  };
  var $S0A = function () {
    return ($S0A = JSIL.Memoize(new JSIL.ConstructorSignature($asm02.System.ArgumentOutOfRangeException, [$asm02.System.String]))) ();
  };
  var $S0B = function () {
    return ($S0B = JSIL.Memoize(new JSIL.ConstructorSignature($asm03.SharpJS.Dom.Element, [$asm02.System.Object]))) ();
  };
  var $S0C = function () {
    return ($S0C = JSIL.Memoize(new JSIL.MethodSignature($asm02.System.Object, [$asm02.System.Type, System.Array.Of($asm02.System.Object)]))) ();
  };
  var $S0D = function () {
    return ($S0D = JSIL.Memoize(new JSIL.MethodSignature($asm02.TypeRef("System.Collections.Generic.IEnumerable`1", ["!!0"]), [$asm02.TypeRef("System.Collections.Generic.IEnumerable`1", ["!!0"]), $asm02.TypeRef("System.Func`2", ["!!0", $asm02.TypeRef("System.Boolean")])], ["TSource"]))) ();
  };
  var $S0E = function () {
    return ($S0E = JSIL.Memoize(new JSIL.MethodSignature($asm02.System.Boolean, [$asm02.System.String]))) ();
  };
  var $IM00 = function () {
    return ($IM00 = JSIL.Memoize($asm02.System.Collections.Generic.IEnumerable$b1.Of($asm02.System.String).GetEnumerator)) ();
  };
  var $IM01 = function () {
    return ($IM01 = JSIL.Memoize($asm02.System.Collections.IEnumerator.MoveNext)) ();
  };
  var $IM02 = function () {
    return ($IM02 = JSIL.Memoize($asm02.System.Collections.Generic.IEnumerator$b1.Of($asm02.System.String).get_Current)) ();
  };
  var $IM03 = function () {
    return ($IM03 = JSIL.Memoize($asm02.System.IDisposable.Dispose)) ();
  };


  function Element__ctor$00 (type) {
    $S00().Call($thisType.prototype, "_ctor", null, this, document.createElement(type));
  }; 

  function Element__ctor$01 (elementHandle) {
    this._handlers = $S01().Construct();
    if (elementHandle === null) {
      throw $S02().Construct("elementHandle");
    }
    this.ElementHandle = elementHandle;
    this._selfReference = this;
    this.Element$StyleCollection$value = new ($T04())(this);
  }; 

  function Element__ctor$02 () {
    this._handlers = $S01().Construct();
  }; 

  function Element_$ladd_Change$gb__7_0 (e) {
    this._change(this, new ($T05())());
  }; 

  function Element_$ladd_Click$gb__10_0 (e) {
    this._click(this, new ($T05())());
  }; 

  function Element_$ladd_KeyDown$gb__13_0 (e) {
    this._keyDown(this, new ($T05())());
  }; 

  function Element_$ladd_MouseOut$gb__16_0 (e) {
    this._mouseOut(this, new ($T05())());
  }; 

  function Element_$ladd_MouseOver$gb__19_0 (e) {
    this._mouseOver(this, new ($T05())());
  }; 

  function Element_add__change (value) {
    var eventHandler = this._change;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T07().Combine(eventHandler2, value);
      eventHandler = $T08().CompareExchange$b1($T06())(/* ref */ new JSIL.MemberReference(this, "_change"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function Element_add__click (value) {
    var eventHandler = this._click;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T07().Combine(eventHandler2, value);
      eventHandler = $T08().CompareExchange$b1($T06())(/* ref */ new JSIL.MemberReference(this, "_click"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function Element_add__keyDown (value) {
    var eventHandler = this._keyDown;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T07().Combine(eventHandler2, value);
      eventHandler = $T08().CompareExchange$b1($T06())(/* ref */ new JSIL.MemberReference(this, "_keyDown"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function Element_add__mouseOut (value) {
    var eventHandler = this._mouseOut;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T07().Combine(eventHandler2, value);
      eventHandler = $T08().CompareExchange$b1($T06())(/* ref */ new JSIL.MemberReference(this, "_mouseOut"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function Element_add__mouseOver (value) {
    var eventHandler = this._mouseOver;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T07().Combine(eventHandler2, value);
      eventHandler = $T08().CompareExchange$b1($T06())(/* ref */ new JSIL.MemberReference(this, "_mouseOver"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function Element_add_Change (value) {
    this.AddNativeHandler("change", $T09().New(this, null, new JSIL.MethodPointerInfo($thisType, "$ladd_Change$gb__7_0", $S03(), false, false)));
    this.add__change(value);
  }; 

  function Element_add_Click (value) {
    this.AddNativeHandler("click", $T09().New(this, null, new JSIL.MethodPointerInfo($thisType, "$ladd_Click$gb__10_0", $S04(), false, false)));
    this.add__click(value);
  }; 

  function Element_add_KeyDown (value) {
    this.AddNativeHandler("keydown", $T09().New(this, null, new JSIL.MethodPointerInfo($thisType, "$ladd_KeyDown$gb__13_0", $S05(), false, false)));
    this.add__keyDown(value);
  }; 

  function Element_add_MouseOut (value) {
    this.AddNativeHandler("mouseout", $T09().New(this, null, new JSIL.MethodPointerInfo($thisType, "$ladd_MouseOut$gb__16_0", $S06(), false, false)));
    this.add__mouseOut(value);
  }; 

  function Element_add_MouseOver (value) {
    this.AddNativeHandler("mouseover", $T09().New(this, null, new JSIL.MethodPointerInfo($thisType, "$ladd_MouseOver$gb__19_0", $S07(), false, false)));
    this.add__mouseOver(value);
  }; 

  function Element_AddNativeHandler (eventName, handler) {
    if (!((this._handlers).ContainsKey(eventName) && ((this._handlers).get_Item(eventName) !== null))) {
      var expr_21 = new ($T0A())();
      expr_21.Handler = handler;
      var proxy = expr_21;
      this.ElementHandle.addEventListener(eventName, proxy.Handler);
      (this._handlers).set_Item(eventName, proxy);
      return;
    }
    (this._handlers).get_Item(eventName).Counter = ((((this._handlers).get_Item(eventName).Counter | 0) + 1) | 0);
  }; 

  function Element_get_Children () {
    var arg_2E_1 = null;
    var arg_2E_0 = $T0D().$Cast($T0E().$Cast(Array.prototype.slice.call(this.ElementHandle.children)));
    if ((arg_2E_1 = $T0F().$l$g9__63_0) === null) {
      arg_2E_1 = $T0F().$l$g9__63_0 = $T0C().New($T0F().$l$g9, null, new JSIL.MethodPointerInfo($asm03.SharpJS.Dom.Element_$l$gc, "$lget_Children$gb__63_0", $S08(), false, false));
    }
    return $T10().ToArray$b1($thisType)($S09().CallStatic($T10(), "Select$b2", [$asm02.System.Object, $thisType], arg_2E_0, arg_2E_1));
  }; 

  function Element_get_Class () {
    return this.get_Item("className");
  }; 

  function Element_get_DOMRepresentation () {
    return this.ElementHandle;
  }; 

  function Element_get_Enabled () {
    return $T11().$Cast(!this.ElementHandle.disabled);
  }; 

  function Element_get_FirstChild () {
    return $thisType.GetElement(this.ElementHandle.firstChild);
  }; 

  function Element_get_Height () {
    return $T12().$Cast(this.ElementHandle.height);
  }; 

  function Element_get_Id () {
    return $T00().$Cast(this.ElementHandle.id);
  }; 

  function Element_get_InnerHtml () {
    return $T00().$Cast(this.ElementHandle.innerHTML);
  }; 

  function Element_get_Item (index) {
    return JSIL.Coalesce(this.ElementHandle[index], $T00().Empty);
  }; 

  function Element_get_NextSibling () {
    return $thisType.GetElement(this.ElementHandle.nextSibling);
  }; 

  function Element_get_OuterHtml () {
    return $T00().$Cast(this.ElementHandle.outerHTML);
  }; 

  function Element_get_Parent () {
    return $thisType.GetElement(this.ElementHandle.parent);
  }; 

  function Element_get_Style () {
    return this.ElementHandle["style"];
  }; 

  function Element_get_StyleCollection () {
    return this.Element$StyleCollection$value;
  }; 

  function Element_get_TagName () {
    return $T00().$Cast(this.ElementHandle.tagName);
  }; 

  function Element_get_TextContent () {
    return $T00().$Cast(this.ElementHandle.textContent);
  }; 

  function Element_get_Width () {
    return $T12().$Cast(this.ElementHandle.width);
  }; 

  function Element_GetById (id) {
    var expr_0F = $thisType.GetElement(document.getElementById(id));
    if (expr_0F === null) {
      throw $S0A().Construct("id");
    }
    return expr_0F;
  }; 

  function Element_GetElement (handle) {
    if (handle === null) {
      return null;
    }
    var obj = (handle._selfReference);
    if (!((obj !== null) && (obj !== (undefined)))) {
      return $S0B().Construct(handle);
    }
    return $thisType.$Cast(obj);
  }; 

  function Element_GetElement$b1 (T, handle) {
    if (handle === null) {
      return (
        T.IsValueType
           ? JSIL.CreateInstanceOfType(T)
           : null)
      ;
    }
    var obj = (handle._selfReference);
    if (!((obj !== null) && (obj !== (undefined)))) {
      return T.$Cast($S0C().CallStatic($T15(), "CreateInstance", null, T, JSIL.Array.New($T01(), [handle])));
    }
    return T.$Cast(obj);
  }; 

  function Element_remove__change (value) {
    var eventHandler = this._change;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T07().Remove(eventHandler2, value);
      eventHandler = $T08().CompareExchange$b1($T06())(/* ref */ new JSIL.MemberReference(this, "_change"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function Element_remove__click (value) {
    var eventHandler = this._click;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T07().Remove(eventHandler2, value);
      eventHandler = $T08().CompareExchange$b1($T06())(/* ref */ new JSIL.MemberReference(this, "_click"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function Element_remove__keyDown (value) {
    var eventHandler = this._keyDown;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T07().Remove(eventHandler2, value);
      eventHandler = $T08().CompareExchange$b1($T06())(/* ref */ new JSIL.MemberReference(this, "_keyDown"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function Element_remove__mouseOut (value) {
    var eventHandler = this._mouseOut;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T07().Remove(eventHandler2, value);
      eventHandler = $T08().CompareExchange$b1($T06())(/* ref */ new JSIL.MemberReference(this, "_mouseOut"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function Element_remove__mouseOver (value) {
    var eventHandler = this._mouseOver;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T07().Remove(eventHandler2, value);
      eventHandler = $T08().CompareExchange$b1($T06())(/* ref */ new JSIL.MemberReference(this, "_mouseOver"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function Element_remove_Change (value) {
    this.RemoveNativehandler("change");
    this.remove__change(value);
  }; 

  function Element_remove_Click (value) {
    this.RemoveNativehandler("click");
    this.remove__click(value);
  }; 

  function Element_remove_KeyDown (value) {
    this.RemoveNativehandler("keydown");
    this.remove__keyDown(value);
  }; 

  function Element_remove_MouseOut (value) {
    this.RemoveNativehandler("mouseout");
    this.remove__mouseOut(value);
  }; 

  function Element_remove_MouseOver (value) {
    this.RemoveNativehandler("mouseover");
    this.remove__mouseOver(value);
  }; 

  function Element_RemoveClass (className) {
    var $closure0 = new ($T16())();
    $closure0.className = className;
    var arg_44_0 = $S0D().CallStatic($T10(), "Where$b1", [$asm02.System.String], JSIL.SplitString(this.ElementHandle["className"], JSIL.Array.New($T18(), [" ", "\t"])), $T1A().New($closure0, null, new JSIL.MethodPointerInfo($asm03.SharpJS.Dom.Element_$l$gc__DisplayClass97_0, "$lRemoveClass$gb__0", $S0E(), false, false)));
    var text = $T00().Empty;
    var enumerator = $IM00().Call(arg_44_0, null);
    try {

      while ($IM01().Call(enumerator, null)) {
        var current = $IM02().Call(enumerator, null);
        text = ((text + " " + current));
      }
    } finally {
      if (enumerator !== null) {
        $IM03().Call(enumerator, null);
      }
    }
    this.ElementHandle["className"] = text;
  }; 

  function Element_RemoveNativehandler (eventName) {
    var proxy = (this._handlers).get_Item(eventName);
    proxy.Counter = (((proxy.Counter | 0) - 1) | 0);
    if ((proxy.Counter | 0) <= 0) {
      this.ElementHandle.removeEventListener(eventName, proxy.Handler);
      (this._handlers).set_Item(eventName, null);
    }
  }; 

  function Element_set_Class (value) {
    this.set_Item("className", value);
  }; 

  function Element_set_Enabled (value) {
    this.ElementHandle.disabled = !value;
  }; 

  function Element_set_Height (value) {
    this.ElementHandle.height = value;
  }; 

  function Element_set_Id (value) {
    this.ElementHandle.id = value;
  }; 

  function Element_set_InnerHtml (value) {
    this.ElementHandle.innerHTML = value;
  }; 

  function Element_set_Item (index, value) {
    this.ElementHandle[index] = value;
  }; 

  function Element_set_OuterHtml (value) {
    this.ElementHandle.outerHTML = value;
  }; 

  function Element_set_Style (value) {
    this.ElementHandle["style"] = value;
  }; 

  function Element_set_StyleCollection (value) {
    this.Element$StyleCollection$value = value;
  }; 

  function Element_set_TagName (value) {
    this.ElementHandle.tagName = value;
  }; 

  function Element_set_TextContent (value) {
    this.ElementHandle.textContent = value;
  }; 

  function Element_set_Width (value) {
    this.ElementHandle.width = value;
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.Object"), 
      Name: "SharpJS.Dom.Element", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 1, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Action($.String), 
      Element__ctor$00
    );

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Action($.Object), 
      Element__ctor$01
    );

    $.Method({Static:false, Public:false}, ".ctor", 
      JSIL.MethodSignature.Void, 
      Element__ctor$02
    );

    $.Method({Static:false, Public:false}, "$ladd_Change$gb__7_0", 
      JSIL.MethodSignature.Action($.Object), 
      Element_$ladd_Change$gb__7_0
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "$ladd_Click$gb__10_0", 
      JSIL.MethodSignature.Action($.Object), 
      Element_$ladd_Click$gb__10_0
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "$ladd_KeyDown$gb__13_0", 
      JSIL.MethodSignature.Action($.Object), 
      Element_$ladd_KeyDown$gb__13_0
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "$ladd_MouseOut$gb__16_0", 
      JSIL.MethodSignature.Action($.Object), 
      Element_$ladd_MouseOut$gb__16_0
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "$ladd_MouseOver$gb__19_0", 
      JSIL.MethodSignature.Action($.Object), 
      Element_$ladd_MouseOver$gb__19_0
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "add__change", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_add__change
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "add__click", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_add__click
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "add__keyDown", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_add__keyDown
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "add__mouseOut", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_add__mouseOut
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "add__mouseOver", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_add__mouseOver
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "add_Change", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_add_Change
    );

    $.Method({Static:false, Public:true }, "add_Click", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_add_Click
    );

    $.Method({Static:false, Public:true }, "add_KeyDown", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_add_KeyDown
    );

    $.Method({Static:false, Public:true }, "add_MouseOut", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_add_MouseOut
    );

    $.Method({Static:false, Public:true }, "add_MouseOver", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_add_MouseOver
    );

    $.Method({Static:false, Public:false}, "AddNativeHandler", 
      new JSIL.MethodSignature(null, [$.String, $asm02.TypeRef("System.Action`1", [$.Object])]), 
      Element_AddNativeHandler
    );

    $.Method({Static:false, Public:true }, "get_Children", 
      JSIL.MethodSignature.Return($jsilcore.TypeRef("System.Array", [$.Type])), 
      Element_get_Children
    );

    $.Method({Static:false, Public:true }, "get_Class", 
      JSIL.MethodSignature.Return($.String), 
      Element_get_Class
    );

    $.Method({Static:false, Public:true }, "get_DOMRepresentation", 
      JSIL.MethodSignature.Return($.Object), 
      Element_get_DOMRepresentation
    );

    $.Method({Static:false, Public:true }, "get_Enabled", 
      JSIL.MethodSignature.Return($.Boolean), 
      Element_get_Enabled
    );

    $.Method({Static:false, Public:true }, "get_FirstChild", 
      JSIL.MethodSignature.Return($.Type), 
      Element_get_FirstChild
    );

    $.Method({Static:false, Public:true }, "get_Height", 
      JSIL.MethodSignature.Return($.Double), 
      Element_get_Height
    );

    $.Method({Static:false, Public:true }, "get_Id", 
      JSIL.MethodSignature.Return($.String), 
      Element_get_Id
    );

    $.Method({Static:false, Public:true }, "get_InnerHtml", 
      JSIL.MethodSignature.Return($.String), 
      Element_get_InnerHtml
    );

    $.Method({Static:false, Public:true }, "get_Item", 
      new JSIL.MethodSignature($.String, [$.String]), 
      Element_get_Item
    );

    $.Method({Static:false, Public:true }, "get_NextSibling", 
      JSIL.MethodSignature.Return($.Type), 
      Element_get_NextSibling
    );

    $.Method({Static:false, Public:true }, "get_OuterHtml", 
      JSIL.MethodSignature.Return($.String), 
      Element_get_OuterHtml
    );

    $.Method({Static:false, Public:true }, "get_Parent", 
      JSIL.MethodSignature.Return($.Type), 
      Element_get_Parent
    );

    $.Method({Static:false, Public:true }, "get_Style", 
      JSIL.MethodSignature.Return($.String), 
      Element_get_Style
    );

    $.Method({Static:false, Public:true }, "get_StyleCollection", 
      JSIL.MethodSignature.Return($asm03.TypeRef("SharpJS.Dom.StyleCollection")), 
      Element_get_StyleCollection
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_TagName", 
      JSIL.MethodSignature.Return($.String), 
      Element_get_TagName
    );

    $.Method({Static:false, Public:true }, "get_TextContent", 
      JSIL.MethodSignature.Return($.String), 
      Element_get_TextContent
    );

    $.Method({Static:false, Public:true }, "get_Width", 
      JSIL.MethodSignature.Return($.Double), 
      Element_get_Width
    );

    $.Method({Static:true , Public:false}, "GetById", 
      new JSIL.MethodSignature($.Type, [$.String]), 
      Element_GetById
    );

    $.Method({Static:true , Public:false}, "GetElement", 
      new JSIL.MethodSignature($.Type, [$.Object]), 
      Element_GetElement
    );

    $.Method({Static:true , Public:false}, "GetElement", 
      new JSIL.MethodSignature("!!0", [$.Object], ["T"]), 
      Element_GetElement$b1
    );

    $.Method({Static:false, Public:false}, "remove__change", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_remove__change
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "remove__click", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_remove__click
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "remove__keyDown", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_remove__keyDown
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "remove__mouseOut", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_remove__mouseOut
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "remove__mouseOver", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_remove__mouseOver
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "remove_Change", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_remove_Change
    );

    $.Method({Static:false, Public:true }, "remove_Click", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_remove_Click
    );

    $.Method({Static:false, Public:true }, "remove_KeyDown", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_remove_KeyDown
    );

    $.Method({Static:false, Public:true }, "remove_MouseOut", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_remove_MouseOut
    );

    $.Method({Static:false, Public:true }, "remove_MouseOver", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      Element_remove_MouseOver
    );

    $.Method({Static:false, Public:true , Virtual:true }, "RemoveClass", 
      JSIL.MethodSignature.Action($.String), 
      Element_RemoveClass
    );

    $.Method({Static:false, Public:false}, "RemoveNativehandler", 
      JSIL.MethodSignature.Action($.String), 
      Element_RemoveNativehandler
    );

    $.Method({Static:false, Public:true }, "set_Class", 
      JSIL.MethodSignature.Action($.String), 
      Element_set_Class
    );

    $.Method({Static:false, Public:true }, "set_Enabled", 
      JSIL.MethodSignature.Action($.Boolean), 
      Element_set_Enabled
    );

    $.Method({Static:false, Public:true }, "set_Height", 
      JSIL.MethodSignature.Action($.Double), 
      Element_set_Height
    );

    $.Method({Static:false, Public:true }, "set_Id", 
      JSIL.MethodSignature.Action($.String), 
      Element_set_Id
    );

    $.Method({Static:false, Public:true }, "set_InnerHtml", 
      JSIL.MethodSignature.Action($.String), 
      Element_set_InnerHtml
    );

    $.Method({Static:false, Public:true }, "set_Item", 
      new JSIL.MethodSignature(null, [$.String, $.String]), 
      Element_set_Item
    );

    $.Method({Static:false, Public:true }, "set_OuterHtml", 
      JSIL.MethodSignature.Action($.String), 
      Element_set_OuterHtml
    );

    $.Method({Static:false, Public:true }, "set_Style", 
      JSIL.MethodSignature.Action($.String), 
      Element_set_Style
    );

    $.Method({Static:false, Public:false}, "set_StyleCollection", 
      JSIL.MethodSignature.Action($asm03.TypeRef("SharpJS.Dom.StyleCollection")), 
      Element_set_StyleCollection
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_TagName", 
      JSIL.MethodSignature.Action($.String), 
      Element_set_TagName
    );

    $.Method({Static:false, Public:true }, "set_TextContent", 
      JSIL.MethodSignature.Action($.String), 
      Element_set_TextContent
    );

    $.Method({Static:false, Public:true }, "set_Width", 
      JSIL.MethodSignature.Action($.Double), 
      Element_set_Width
    );

    $.Field({Static:false, Public:false}, "_change", $asm02.TypeRef("System.EventHandler"))
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Field({Static:false, Public:false}, "_click", $asm02.TypeRef("System.EventHandler"))
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Field({Static:false, Public:false}, "_keyDown", $asm02.TypeRef("System.EventHandler"))
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Field({Static:false, Public:false}, "_mouseOut", $asm02.TypeRef("System.EventHandler"))
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Field({Static:false, Public:false}, "_mouseOver", $asm02.TypeRef("System.EventHandler"))
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Field({Static:false, Public:false, ReadOnly:true }, "_handlers", $asm02.TypeRef("System.Collections.Generic.Dictionary`2", [$.Object, $asm03.TypeRef("SharpJS.Dom.Element+Proxy")]));

    $.Field({Static:false, Public:false}, "ElementHandle", $.Object);

    $.Field({Static:false, Public:false}, "_selfReference", $.Type);

    $.Field({Static:false, Public:false}, "Element$NodeType$value", $.Int32)
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Field({Static:false, Public:false}, "Element$StyleCollection$value", $asm03.TypeRef("SharpJS.Dom.StyleCollection"))
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Property({Static:false, Public:true }, "Item", $.String);

    $.Property({Static:false, Public:true }, "Class", $.String);

    $.Property({Static:false, Public:true }, "Enabled", $.Boolean);

    $.Property({Static:false, Public:true }, "Height", $.Double);

    $.Property({Static:false, Public:true }, "Id", $.String);

    $.Property({Static:false, Public:true }, "TagName", $.String);

    $.Property({Static:false, Public:true }, "Width", $.Double);

    $.Property({Static:false, Public:true }, "Children", $jsilcore.TypeRef("System.Array", [$.Type]));

    $.Property({Static:false, Public:true }, "DOMRepresentation", $.Object);

    $.Property({Static:false, Public:true }, "FirstChild", $.Type);

    $.Property({Static:false, Public:true }, "InnerHtml", $.String);

    $.Property({Static:false, Public:true }, "NextSibling", $.Type);

    $.ExternalProperty({Static:false, Public:true }, "NodeType", $.Int32);

    $.Property({Static:false, Public:true }, "OuterHtml", $.String);

    $.Property({Static:false, Public:true }, "Parent", $.Type);

    $.Property({Static:false, Public:true }, "StyleCollection", $asm03.TypeRef("SharpJS.Dom.StyleCollection"));

    $.Property({Static:false, Public:true }, "Style", $.String);

    $.Property({Static:false, Public:true }, "TextContent", $.String);

    $.Event({Static:false, Public:true }, "Change", $asm02.TypeRef("System.EventHandler"));

    $.Event({Static:false, Public:true }, "Click", $asm02.TypeRef("System.EventHandler"));

    $.Event({Static:false, Public:true }, "KeyDown", $asm02.TypeRef("System.EventHandler"));

    $.Event({Static:false, Public:true }, "MouseOut", $asm02.TypeRef("System.EventHandler"));

    $.Event({Static:false, Public:true }, "MouseOver", $asm02.TypeRef("System.EventHandler"));

    $.Event({Static:false, Public:false}, "_change", $asm02.TypeRef("System.EventHandler"));

    $.Event({Static:false, Public:false}, "_click", $asm02.TypeRef("System.EventHandler"));

    $.Event({Static:false, Public:false}, "_keyDown", $asm02.TypeRef("System.EventHandler"));

    $.Event({Static:false, Public:false}, "_mouseOut", $asm02.TypeRef("System.EventHandler"));

    $.Event({Static:false, Public:false}, "_mouseOver", $asm02.TypeRef("System.EventHandler"));


    return function (newThisType) { $thisType = newThisType; }; 
  })
    .Attribute($asm02.TypeRef("System.Reflection.DefaultMemberAttribute"), function () { return ["Item"]; });

})();

/* class SharpJS.Dom.Element+Proxy */ 

(function Proxy$Members () {
  var $, $thisType;

  function Proxy__ctor () {
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.Object"), 
      Name: "SharpJS.Dom.Element+Proxy", 
      IsPublic: false, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      Proxy__ctor
    );

    $.Field({Static:false, Public:true }, "Counter", $.Int32);

    $.Field({Static:false, Public:true }, "Handler", $asm02.TypeRef("System.Action`1", [$.Object]));


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.Element+<>c */ 

(function $l$gc$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.Object)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };


  function $l$gc__ctor () {
  }; 

  function $l$gc_$lget_Children$gb__63_0 (elementObject) {
    return $T01().GetElement(elementObject);
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.Object"), 
      Name: "SharpJS.Dom.Element+<>c", 
      IsPublic: false, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      $l$gc__ctor
    );

    $.Method({Static:false, Public:false}, "$lget_Children$gb__63_0", 
      new JSIL.MethodSignature($asm03.TypeRef("SharpJS.Dom.Element"), [$.Object]), 
      $l$gc_$lget_Children$gb__63_0
    );

    $.Field({Static:true , Public:true , ReadOnly:true }, "$l$g9", $.Type);

    $.Field({Static:true , Public:true }, "$l$g9__63_0", $asm02.TypeRef("System.Func`2", [$.Object, $asm03.TypeRef("SharpJS.Dom.Element")]));


    function $l$gc__cctor () {
      $thisType.$l$g9 = new $thisType();
    }; 

    $.Method({Static:true , Public:false}, ".cctor", 
      JSIL.MethodSignature.Void, 
      $l$gc__cctor
    );


    return function (newThisType) { $thisType = newThisType; }; 
  })
    .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

})();

/* class SharpJS.Dom.Element+<>c__DisplayClass97_0 */ 

(function $l$gc__DisplayClass97_0$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.String)) ();
  };


  function $l$gc__DisplayClass97_0__ctor () {
  }; 

  function $l$gc__DisplayClass97_0_$lRemoveClass$gb__0 (s) {
    return s != this.className;
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.Object"), 
      Name: "SharpJS.Dom.Element+<>c__DisplayClass97_0", 
      IsPublic: false, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      $l$gc__DisplayClass97_0__ctor
    );

    $.Method({Static:false, Public:false}, "$lRemoveClass$gb__0", 
      new JSIL.MethodSignature($.Boolean, [$.String]), 
      $l$gc__DisplayClass97_0_$lRemoveClass$gb__0
    );

    $.Field({Static:false, Public:true }, "className", $.String);


    return function (newThisType) { $thisType = newThisType; }; 
  })
    .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

})();

/* class SharpJS.Dom.IntervalDispatcher */ 

(function IntervalDispatcher$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.TimeSpan)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm02.System.EventHandler)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm02.System.Delegate)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm02.System.Threading.Interlocked)) ();
  };
  var $T04 = function () {
    return ($T04 = JSIL.Memoize($asm02.System.EventArgs)) ();
  };


  function IntervalDispatcher__ctor (timeSpan) {
    (this.IntervalDispatcher$Interval$value = timeSpan.MemberwiseClone());
  }; 

  function IntervalDispatcher_add_Tick (value) {
    var eventHandler = this.Tick;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T02().Combine(eventHandler2, value);
      eventHandler = $T03().CompareExchange$b1($T01())(/* ref */ new JSIL.MemberReference(this, "Tick"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function IntervalDispatcher_get_Interval () {
    return this.IntervalDispatcher$Interval$value;
  }; 

  function IntervalDispatcher_OnNativeEvent () {
    if (this.Tick !== null) {
      this.Tick(this, $T04().Empty);
    }
  }; 

  function IntervalDispatcher_remove_Tick (value) {
    var eventHandler = this.Tick;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T02().Remove(eventHandler2, value);
      eventHandler = $T03().CompareExchange$b1($T01())(/* ref */ new JSIL.MemberReference(this, "Tick"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function IntervalDispatcher_set_Interval (value) {
    this.IntervalDispatcher$Interval$value = value.MemberwiseClone();
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.Object"), 
      Name: "SharpJS.Dom.IntervalDispatcher", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 1, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.TimeSpan")), 
      IntervalDispatcher__ctor
    );

    $.Method({Static:false, Public:true }, "add_Tick", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      IntervalDispatcher_add_Tick
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_Interval", 
      JSIL.MethodSignature.Return($asm02.TypeRef("System.TimeSpan")), 
      IntervalDispatcher_get_Interval
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "OnNativeEvent", 
      JSIL.MethodSignature.Void, 
      IntervalDispatcher_OnNativeEvent
    );

    $.Method({Static:false, Public:true }, "remove_Tick", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      IntervalDispatcher_remove_Tick
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "set_Interval", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.TimeSpan")), 
      IntervalDispatcher_set_Interval
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Field({Static:false, Public:false}, "_handle", $.Object);

    $.Field({Static:false, Public:false}, "IntervalDispatcher$Interval$value", $asm02.TypeRef("System.TimeSpan"))
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Field({Static:false, Public:false}, "Tick", $asm02.TypeRef("System.EventHandler"))
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Property({Static:false, Public:true }, "Interval", $asm02.TypeRef("System.TimeSpan"));

    $.Event({Static:false, Public:true }, "Tick", $asm02.TypeRef("System.EventHandler"));


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.JSConsole */ 

(function JSConsole$Members () {
  var $, $thisType;

  JSIL.MakeStaticClass("SharpJS.Dom.JSConsole", true, [], function ($ib) {
    $ = $ib;


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.JSLibrary */ 

(function JSLibrary$Members () {
  var $, $thisType;

  JSIL.MakeStaticClass("SharpJS.Dom.JSLibrary", true, [], function ($ib) {
    $ = $ib;


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.Style */ 

(function Style$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm03.SharpJS.Dom.StringStyle)) ();
  };


  function Style__ctor () {
  }; 

  function Style_Parse (s) {
    return new ($T01())(s);
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.Object"), 
      Name: "SharpJS.Dom.Style", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:false}, ".ctor", 
      JSIL.MethodSignature.Void, 
      Style__ctor
    );

    $.Method({Static:true , Public:true }, "Parse", 
      new JSIL.MethodSignature($.Type, [$.String]), 
      Style_Parse
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.RgbStyle */ 

(function RgbStyle$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm03.SharpJS.Dom.Style)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm02.System.Byte)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm02.System.String)) ();
  };


  function RgbStyle__ctor$00 () {
    $T00().prototype._ctor.call(this);
  }; 

  function RgbStyle__ctor$01 (red, green, blue) {
    $T00().prototype._ctor.call(this);
    this.RgbStyle$Red$value = (red | 0);
    this.RgbStyle$Green$value = (green | 0);
    this.RgbStyle$Blue$value = (blue | 0);
  }; 

  function RgbStyle_get_Blue () {
    return this.RgbStyle$Blue$value;
  }; 

  function RgbStyle_get_Green () {
    return this.RgbStyle$Green$value;
  }; 

  function RgbStyle_get_Red () {
    return this.RgbStyle$Red$value;
  }; 

  function RgbStyle_set_Blue (value) {
    this.RgbStyle$Blue$value = (value | 0);
  }; 

  function RgbStyle_set_Green (value) {
    this.RgbStyle$Green$value = (value | 0);
  }; 

  function RgbStyle_set_Red (value) {
    this.RgbStyle$Red$value = (value | 0);
  }; 

  function RgbStyle_toString () {
    return $T02().Format("rgb({0},{1},{2})", $T01().$Box(this.RgbStyle$Red$value), $T01().$Box(this.RgbStyle$Green$value), $T01().$Box(this.RgbStyle$Blue$value));
  }; 

  JSIL.MakeType({
      BaseType: $asm03.TypeRef("SharpJS.Dom.Style"), 
      Name: "SharpJS.Dom.RgbStyle", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 3, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      RgbStyle__ctor$00
    );

    $.Method({Static:false, Public:true }, ".ctor", 
      new JSIL.MethodSignature(null, [
          $.Byte, $.Byte, 
          $.Byte
        ]), 
      RgbStyle__ctor$01
    );

    $.Method({Static:false, Public:true }, "get_Blue", 
      JSIL.MethodSignature.Return($.Byte), 
      RgbStyle_get_Blue
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_Green", 
      JSIL.MethodSignature.Return($.Byte), 
      RgbStyle_get_Green
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_Red", 
      JSIL.MethodSignature.Return($.Byte), 
      RgbStyle_get_Red
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Blue", 
      JSIL.MethodSignature.Action($.Byte), 
      RgbStyle_set_Blue
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Green", 
      JSIL.MethodSignature.Action($.Byte), 
      RgbStyle_set_Green
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Red", 
      JSIL.MethodSignature.Action($.Byte), 
      RgbStyle_set_Red
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true , Virtual:true }, "toString", 
      JSIL.MethodSignature.Return($.String), 
      RgbStyle_toString
    );

    $.Field({Static:false, Public:false}, "RgbStyle$Red$value", $.Byte)
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Field({Static:false, Public:false}, "RgbStyle$Green$value", $.Byte)
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Field({Static:false, Public:false}, "RgbStyle$Blue$value", $.Byte)
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Property({Static:false, Public:true }, "Red", $.Byte);

    $.Property({Static:false, Public:true }, "Green", $.Byte);

    $.Property({Static:false, Public:true }, "Blue", $.Byte);


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.StringStyle */ 

(function StringStyle$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm03.SharpJS.Dom.Style)) ();
  };


  function StringStyle__ctor (s) {
    $T01().prototype._ctor.call(this);
    this.s = s;
  }; 

  function StringStyle_toString () {
    return this.s;
  }; 

  JSIL.MakeType({
      BaseType: $asm03.TypeRef("SharpJS.Dom.Style"), 
      Name: "SharpJS.Dom.StringStyle", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 1, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Action($.String), 
      StringStyle__ctor
    );

    $.Method({Static:false, Public:true , Virtual:true }, "toString", 
      JSIL.MethodSignature.Return($.String), 
      StringStyle_toString
    );

    $.Field({Static:false, Public:false, ReadOnly:true }, "s", $.String);


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.StyleCollection */ 

(function StyleCollection$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm02.System.NotImplementedException)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(new JSIL.ConstructorSignature($asm02.System.NotImplementedException, null))) ();
  };


  function StyleCollection__ctor (element) {
    this._parent = element;
  }; 

  function StyleCollection_Add (name, value) {
    this._parent.ElementHandle.style[name] = value;
  }; 

  function StyleCollection_GetEnumerator () {
    throw $S00().Construct();
  }; 

  function StyleCollection_System_Collections_IEnumerable_GetEnumerator () {
    throw $S00().Construct();
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.Object"), 
      Name: "SharpJS.Dom.StyleCollection", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 1, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Action($asm03.TypeRef("SharpJS.Dom.Element")), 
      StyleCollection__ctor
    );

    $.Method({Static:false, Public:true }, "Add", 
      new JSIL.MethodSignature(null, [$.String, $.String]), 
      StyleCollection_Add
    );

    $.Method({Static:false, Public:true , Virtual:true }, "GetEnumerator", 
      JSIL.MethodSignature.Return($asm02.TypeRef("System.Collections.Generic.IEnumerator`1", [$.Object])), 
      StyleCollection_GetEnumerator
    );

    $.Method({Static:false, Public:false, Virtual:true }, "System.Collections.IEnumerable.GetEnumerator", 
      JSIL.MethodSignature.Return($asm02.TypeRef("System.Collections.IEnumerator")), 
      StyleCollection_System_Collections_IEnumerable_GetEnumerator
    )
      .Overrides($asm02.TypeRef("System.Collections.IEnumerable"), "GetEnumerator");

    $.Field({Static:false, Public:false}, "_parent", $asm03.TypeRef("SharpJS.Dom.Element"));

    $.ImplementInterfaces(
      /* 0 */ $asm02.TypeRef("System.Collections.Generic.IEnumerable`1", [$.Object]), 
      /* 1 */ $asm02.TypeRef("System.Collections.IEnumerable")
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

JSIL.DeclareNamespace("SharpJS.Dom.Styles");
/* enum SharpJS.Dom.Styles.FontWeight */ 

JSIL.MakeEnum(
  {
    FullName: "SharpJS.Dom.Styles.FontWeight", 
    BaseType: $asm02.TypeRef("System.Int32"), 
    IsPublic: true, 
    IsFlags: false, 
  }, 
  {
    Normal: 0, 
    Bold: 1, 
    Bolder: 2, 
    Lighter: 3, 
  }
);

/* enum SharpJS.Dom.Styles.TextAlign */ 

JSIL.MakeEnum(
  {
    FullName: "SharpJS.Dom.Styles.TextAlign", 
    BaseType: $asm02.TypeRef("System.Int32"), 
    IsPublic: true, 
    IsFlags: false, 
  }, 
  {
    Left: 0, 
    Right: 1, 
    Center: 2, 
    Justify: 3, 
  }
);

JSIL.DeclareNamespace("SharpJS.Dom.Elements");
/* class SharpJS.Dom.Elements.AnchorElement */ 

(function AnchorElement$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.String")))) ();
  };


  function AnchorElement__ctor () {
    $S00().Call($T00().prototype, "_ctor", null, this, "a");
  }; 

  function AnchorElement_get_Href () {
    return this.get_Item("href");
  }; 

  function AnchorElement_set_Href (value) {
    this.set_Item("href", value);
  }; 

  JSIL.MakeType({
      BaseType: $asm03.TypeRef("SharpJS.Dom.Element"), 
      Name: "SharpJS.Dom.Elements.AnchorElement", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      AnchorElement__ctor
    );

    $.Method({Static:false, Public:true }, "get_Href", 
      JSIL.MethodSignature.Return($.String), 
      AnchorElement_get_Href
    );

    $.Method({Static:false, Public:true }, "set_Href", 
      JSIL.MethodSignature.Action($.String), 
      AnchorElement_set_Href
    );

    $.Property({Static:false, Public:true }, "Href", $.String);


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.Elements.ButtonElement */ 

(function ButtonElement$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.String")))) ();
  };


  function ButtonElement__ctor () {
    $S00().Call($T00().prototype, "_ctor", null, this, "button");
  }; 

  JSIL.MakeType({
      BaseType: $asm03.TypeRef("SharpJS.Dom.Element"), 
      Name: "SharpJS.Dom.Elements.ButtonElement", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      ButtonElement__ctor
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.Elements.CanvasElement */ 

(function CanvasElement$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.String")))) ();
  };


  function CanvasElement__ctor () {
    $S00().Call($T00().prototype, "_ctor", null, this, "canvas");
  }; 

  JSIL.MakeType({
      BaseType: $asm03.TypeRef("SharpJS.Dom.Element"), 
      Name: "SharpJS.Dom.Elements.CanvasElement", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      CanvasElement__ctor
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.Elements.DivElement */ 

(function DivElement$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.String")))) ();
  };


  function DivElement__ctor () {
    $S00().Call($T00().prototype, "_ctor", null, this, "div");
    this.set_Item("tabIndex", "-1");
  }; 

  JSIL.MakeType({
      BaseType: $asm03.TypeRef("SharpJS.Dom.Element"), 
      Name: "SharpJS.Dom.Elements.DivElement", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      DivElement__ctor
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.Elements.FormElement */ 

(function FormElement$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.String")))) ();
  };


  function FormElement__ctor () {
    $S00().Call($T00().prototype, "_ctor", null, this, "form");
  }; 

  JSIL.MakeType({
      BaseType: $asm03.TypeRef("SharpJS.Dom.Element"), 
      Name: "SharpJS.Dom.Elements.FormElement", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      FormElement__ctor
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.Elements.HeaderElement */ 

(function HeaderElement$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.Int32)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.String")))) ();
  };


  function HeaderElement__ctor (size) {
    $S00().Call($T01().prototype, "_ctor", null, this, JSIL.ConcatString("h", $T00().$Box(size)));
  }; 

  JSIL.MakeType({
      BaseType: $asm03.TypeRef("SharpJS.Dom.Element"), 
      Name: "SharpJS.Dom.Elements.HeaderElement", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 1, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Action($.Int32), 
      HeaderElement__ctor
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.Elements.IFrameElement */ 

(function IFrameElement$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.String")))) ();
  };


  function IFrameElement__ctor () {
    $S00().Call($T00().prototype, "_ctor", null, this, "iframe");
  }; 

  function IFrameElement_get_Source () {
    return this.get_Item("src");
  }; 

  function IFrameElement_set_Source (value) {
    this.set_Item("src", value);
  }; 

  JSIL.MakeType({
      BaseType: $asm03.TypeRef("SharpJS.Dom.Element"), 
      Name: "SharpJS.Dom.Elements.IFrameElement", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      IFrameElement__ctor
    );

    $.Method({Static:false, Public:true }, "get_Source", 
      JSIL.MethodSignature.Return($.String), 
      IFrameElement_get_Source
    );

    $.Method({Static:false, Public:true }, "set_Source", 
      JSIL.MethodSignature.Action($.String), 
      IFrameElement_set_Source
    );

    $.Property({Static:false, Public:true }, "Source", $.String);


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.Elements.ImageElement */ 

(function ImageElement$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.String")))) ();
  };


  function ImageElement__ctor () {
    $S00().Call($T00().prototype, "_ctor", null, this, "img");
  }; 

  JSIL.MakeType({
      BaseType: $asm03.TypeRef("SharpJS.Dom.Element"), 
      Name: "SharpJS.Dom.Elements.ImageElement", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      ImageElement__ctor
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.Elements.FileUploadElement */ 

(function FileUploadElement$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm02.System.Boolean)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.String")))) ();
  };


  function FileUploadElement__ctor () {
    $S00().Call($T00().prototype, "_ctor", null, this, "input");
    this.set_Item("type", "file");
  }; 

  function FileUploadElement_set_Hidden (value) {
    this.set_Style((
        value
           ? "display:none;"
           : "display:inline;")
    );
  }; 

  JSIL.MakeType({
      BaseType: $asm03.TypeRef("SharpJS.Dom.Element"), 
      Name: "SharpJS.Dom.Elements.FileUploadElement", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      FileUploadElement__ctor
    );

    $.Method({Static:false, Public:true }, "set_Hidden", 
      JSIL.MethodSignature.Action($.Boolean), 
      FileUploadElement_set_Hidden
    );

    $.Property({Static:false, Public:true }, "Hidden", $.Boolean);


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.Elements.InputElement */ 

(function InputElement$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.String")))) ();
  };


  function InputElement__ctor () {
    $S00().Call($T00().prototype, "_ctor", null, this, "input");
  }; 

  function InputElement_get_Type () {
    return this.get_Item("type");
  }; 

  function InputElement_set_Type (value) {
    this.set_Item("type", value);
  }; 

  JSIL.MakeType({
      BaseType: $asm03.TypeRef("SharpJS.Dom.Element"), 
      Name: "SharpJS.Dom.Elements.InputElement", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      InputElement__ctor
    );

    $.Method({Static:false, Public:true }, "get_Type", 
      JSIL.MethodSignature.Return($.String), 
      InputElement_get_Type
    );

    $.Method({Static:false, Public:true }, "set_Type", 
      JSIL.MethodSignature.Action($.String), 
      InputElement_set_Type
    );

    $.Property({Static:false, Public:true }, "Type", $.String);


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.Elements.LinkElement */ 

(function LinkElement$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.String")))) ();
  };


  function LinkElement__ctor () {
    $S00().Call($T00().prototype, "_ctor", null, this, "link");
  }; 

  function LinkElement_get_Href () {
    return this.get_Item("href");
  }; 

  function LinkElement_get_Relation () {
    return this.get_Item("rel");
  }; 

  function LinkElement_get_Type () {
    return this.get_Item("type");
  }; 

  function LinkElement_set_Href (value) {
    this.set_Item("href", value);
  }; 

  function LinkElement_set_Relation (value) {
    this.set_Item("rel", value);
  }; 

  function LinkElement_set_Type (value) {
    this.set_Item("type", value);
  }; 

  JSIL.MakeType({
      BaseType: $asm03.TypeRef("SharpJS.Dom.Element"), 
      Name: "SharpJS.Dom.Elements.LinkElement", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      LinkElement__ctor
    );

    $.Method({Static:false, Public:true }, "get_Href", 
      JSIL.MethodSignature.Return($.String), 
      LinkElement_get_Href
    );

    $.Method({Static:false, Public:true }, "get_Relation", 
      JSIL.MethodSignature.Return($.String), 
      LinkElement_get_Relation
    );

    $.Method({Static:false, Public:true }, "get_Type", 
      JSIL.MethodSignature.Return($.String), 
      LinkElement_get_Type
    );

    $.Method({Static:false, Public:true }, "set_Href", 
      JSIL.MethodSignature.Action($.String), 
      LinkElement_set_Href
    );

    $.Method({Static:false, Public:true }, "set_Relation", 
      JSIL.MethodSignature.Action($.String), 
      LinkElement_set_Relation
    );

    $.Method({Static:false, Public:true }, "set_Type", 
      JSIL.MethodSignature.Action($.String), 
      LinkElement_set_Type
    );

    $.Property({Static:false, Public:true }, "Href", $.String);

    $.Property({Static:false, Public:true }, "Type", $.String);

    $.Property({Static:false, Public:true }, "Relation", $.String);


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.Elements.TextAreaElement */ 

(function TextAreaElement$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm02.System.Int32)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.String")))) ();
  };


  function TextAreaElement__ctor () {
    $S00().Call($T00().prototype, "_ctor", null, this, "textarea");
  }; 

  function TextAreaElement_get_Columns () {
    return $T01().Parse(this.get_Item("cols"));
  }; 

  function TextAreaElement_get_Rows () {
    return $T01().Parse(this.get_Item("rows"));
  }; 

  function TextAreaElement_set_Columns (value) {
    this.set_Item("cols", (value).toString());
  }; 

  function TextAreaElement_set_Rows (value) {
    this.set_Item("rows", (value).toString());
  }; 

  JSIL.MakeType({
      BaseType: $asm03.TypeRef("SharpJS.Dom.Element"), 
      Name: "SharpJS.Dom.Elements.TextAreaElement", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      TextAreaElement__ctor
    );

    $.Method({Static:false, Public:true }, "get_Columns", 
      JSIL.MethodSignature.Return($.Int32), 
      TextAreaElement_get_Columns
    );

    $.Method({Static:false, Public:true }, "get_Rows", 
      JSIL.MethodSignature.Return($.Int32), 
      TextAreaElement_get_Rows
    );

    $.Method({Static:false, Public:true }, "set_Columns", 
      JSIL.MethodSignature.Action($.Int32), 
      TextAreaElement_set_Columns
    );

    $.Method({Static:false, Public:true }, "set_Rows", 
      JSIL.MethodSignature.Action($.Int32), 
      TextAreaElement_set_Rows
    );

    $.Property({Static:false, Public:true }, "Rows", $.Int32);

    $.Property({Static:false, Public:true }, "Columns", $.Int32);


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.Elements.ParagraphElement */ 

(function ParagraphElement$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.String")))) ();
  };


  function ParagraphElement__ctor () {
    $S00().Call($T00().prototype, "_ctor", null, this, "p");
  }; 

  JSIL.MakeType({
      BaseType: $asm03.TypeRef("SharpJS.Dom.Element"), 
      Name: "SharpJS.Dom.Elements.ParagraphElement", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      ParagraphElement__ctor
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.Elements.PreformattedElement */ 

(function PreformattedElement$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.String")))) ();
  };


  function PreformattedElement__ctor () {
    $S00().Call($T00().prototype, "_ctor", null, this, "pre");
  }; 

  JSIL.MakeType({
      BaseType: $asm03.TypeRef("SharpJS.Dom.Element"), 
      Name: "SharpJS.Dom.Elements.PreformattedElement", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      PreformattedElement__ctor
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.Dom.Elements.ScriptElement */ 

(function ScriptElement$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.String")))) ();
  };


  function ScriptElement__ctor () {
    $S00().Call($T00().prototype, "_ctor", null, this, "script");
  }; 

  function ScriptElement_get_Source () {
    return this.get_Item("src");
  }; 

  function ScriptElement_set_Source (value) {
    this.set_Item("src", value);
  }; 

  JSIL.MakeType({
      BaseType: $asm03.TypeRef("SharpJS.Dom.Element"), 
      Name: "SharpJS.Dom.Elements.ScriptElement", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      ScriptElement__ctor
    );

    $.Method({Static:false, Public:true }, "get_Source", 
      JSIL.MethodSignature.Return($.String), 
      ScriptElement_get_Source
    );

    $.Method({Static:false, Public:true }, "set_Source", 
      JSIL.MethodSignature.Action($.String), 
      ScriptElement_set_Source
    );

    $.Property({Static:false, Public:true }, "Source", $.String);


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

JSIL.DeclareNamespace("SharpJS.Dom.Attributes");
/* enum SharpJS.Dom.Attributes.InputType */ 

JSIL.MakeEnum(
  {
    FullName: "SharpJS.Dom.Attributes.InputType", 
    BaseType: $asm02.TypeRef("System.Int32"), 
    IsPublic: true, 
    IsFlags: false, 
  }, 
  {
    Text: 0, 
    Password: 1, 
    Email: 2, 
    Number: 3, 
    Search: 4, 
  }
);

