/* Generated by JSIL v0.8.2 build 30533. See http://jsil.org/ for more information. */ 
'use strict';
var $asm0A = JSIL.DeclareAssembly("WebFormsApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null");

JSIL.SetEntryPoint($asm0A, $asm0A.TypeRef("WebFormsApp1.WebFormsApplication"), "Main", JSIL.MethodSignature.Action($jsilcore.TypeRef("System.Array", [$asm02.TypeRef("System.String")])));

JSIL.DeclareNamespace("WebFormsApp1");
/* class WebFormsApp1.MainForm */ 

(function MainForm$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.Action)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm01.ExaPhaser.WebForms.WebForm)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm01.ExaPhaser.WebForms.Layout)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm01.ExaPhaser.WebForms.Controls.TextBlock)) ();
  };
  var $T04 = function () {
    return ($T04 = JSIL.Memoize($asm01.ExaPhaser.WebForms.Controls.TextControl)) ();
  };
  var $T05 = function () {
    return ($T05 = JSIL.Memoize($asm03.SharpJS.Dom.Styles.TextAlign)) ();
  };
  var $T06 = function () {
    return ($T06 = JSIL.Memoize($asm01.ExaPhaser.WebForms.FontStyle)) ();
  };
  var $T07 = function () {
    return ($T07 = JSIL.Memoize($asm03.SharpJS.Dom.Styles.FontWeight)) ();
  };
  var $T08 = function () {
    return ($T08 = JSIL.Memoize($asm01.ExaPhaser.WebForms.Control)) ();
  };
  var $T09 = function () {
    return ($T09 = JSIL.Memoize($asm02.System.Collections.ObjectModel.Collection$b1.Of($asm01.ExaPhaser.WebForms.Control))) ();
  };
  var $T0A = function () {
    return ($T0A = JSIL.Memoize($asm01.ExaPhaser.WebForms.Controls.TextBox)) ();
  };
  var $T0B = function () {
    return ($T0B = JSIL.Memoize($asm01.ExaPhaser.WebForms.Controls.Button)) ();
  };
  var $T0C = function () {
    return ($T0C = JSIL.Memoize($asm0A.WebFormsApp1.MainForm_$l$gc)) ();
  };
  var $T0D = function () {
    return ($T0D = JSIL.Memoize($asm01.ExaPhaser.WebForms.DelegateCommand)) ();
  };
  var $T0E = function () {
    return ($T0E = JSIL.Memoize($asm01.ExaPhaser.WebForms.Controls.TextArea)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(new JSIL.MethodSignature(null, [$asm01.TypeRef("ExaPhaser.WebForms.Control")]))) ();
  };
  var $S01 = function () {
    return ($S01 = JSIL.Memoize(JSIL.MethodSignature.Void)) ();
  };


  function MainForm__ctor () {
    var arg_AD_0 = null;
    $T01().prototype._ctor.call(this);
    var expr_0E = new ($T02())();
    var expr_14 = new ($T03())();
    expr_14.set_Text("SharpJS - ExaPhaser.WebForms Demo");
    expr_14.set_TextAlign($T05().Center);
    var expr_2E = new ($T06())();
    expr_2E.FontStyle$FontSize$value = 24;
    expr_2E.FontStyle$FontWeight$value = $T07().Bold;
    expr_14.set_FontStyle(expr_2E);
    $S00().CallVirtual("Add", null, expr_0E, expr_14);
    var expr_51 = new ($T03())();
    expr_51.set_Text("A random TextBox is below");
    $S00().CallVirtual("Add", null, expr_0E, expr_51);
    var expr_69 = new ($T0A())();
    expr_69.set_PlaceholderText("Placeholder Stuff");
    $S00().CallVirtual("Add", null, expr_0E, expr_69);
    var expr_81 = new ($T0B())();
    expr_81.set_Text("OK");
    if ((arg_AD_0 = $T0C().$l$g9__0_0) === null) {
      arg_AD_0 = $T0C().$l$g9__0_0 = $T00().New($T0C().$l$g9, null, new JSIL.MethodPointerInfo($asm0A.WebFormsApp1.MainForm_$l$gc, "$l_ctor$gb__0_0", $S01(), false, false));
    }
    expr_81.Button$Command$value = new ($T0D())(arg_AD_0);
    $S00().CallVirtual("Add", null, expr_0E, expr_81);
    var expr_C4 = new ($T0E())();
    expr_C4.set_PlaceholderText("This awesome placeholder!");
    expr_C4.set_Rows(20);
    $S00().CallVirtual("Add", null, expr_0E, expr_C4);
    this.set_Controls(expr_0E);
  }; 

  JSIL.MakeType({
      BaseType: $asm01.TypeRef("ExaPhaser.WebForms.WebForm"), 
      Name: "WebFormsApp1.MainForm", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      MainForm__ctor
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class WebFormsApp1.MainForm+<>c */ 

(function $l$gc$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm03.SharpJS.Dom.JSLibrary)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm02.System.String)) ();
  };


  function $l$gc__ctor () {
  }; 

  function $l$gc_$l_ctor$gb__0_0 () {
    alert("You clicked the button");
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.Object"), 
      Name: "WebFormsApp1.MainForm+<>c", 
      IsPublic: false, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      $l$gc__ctor
    );

    $.Method({Static:false, Public:false}, "$l.ctor$gb__0_0", 
      JSIL.MethodSignature.Void, 
      $l$gc_$l_ctor$gb__0_0
    );

    $.Field({Static:true , Public:true , ReadOnly:true }, "$l$g9", $.Type);

    $.Field({Static:true , Public:true }, "$l$g9__0_0", $asm02.TypeRef("System.Action"));


    function $l$gc__cctor () {
      $thisType.$l$g9 = new $thisType();
    }; 

    $.Method({Static:true , Public:false}, ".cctor", 
      JSIL.MethodSignature.Void, 
      $l$gc__cctor
    );


    return function (newThisType) { $thisType = newThisType; }; 
  })
    .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

})();

/* class WebFormsApp1.WebFormsApplication */ 

(function WebFormsApplication$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize(System.Array.Of($asm02.System.String))) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm01.ExaPhaser.WebForms.WebApplication)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm01.ExaPhaser.WebForms.Themes.CSSUITheme)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm01.ExaPhaser.WebForms.Themes.CSSFramework)) ();
  };
  var $T04 = function () {
    return ($T04 = JSIL.Memoize($asm0A.WebFormsApp1.MainForm)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(new JSIL.MethodSignature(null, [$asm01.ExaPhaser.WebForms.WebForm, $asm02.System.String]))) ();
  };


  function WebFormsApplication__ctor () {
  }; 

  function WebFormsApplication_Main (args) {
    $S00().CallVirtual("Run", null, (new ($T01())(new ($T02())($T03().MaterialBootstrap))), new ($T04())(), "webform-container");
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.Object"), 
      Name: "WebFormsApp1.WebFormsApplication", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      WebFormsApplication__ctor
    );

    $.Method({Static:true , Public:true }, "Main", 
      JSIL.MethodSignature.Action($jsilcore.TypeRef("System.Array", [$.String])), 
      WebFormsApplication_Main
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

