/* Generated by JSIL v0.8.2 build 30533. See http://jsil.org/ for more information. */ 
'use strict';
var $asm04 = JSIL.DeclareAssembly("SharpJS.JSLibraries, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null");

JSIL.DeclareNamespace("SharpJS");
JSIL.DeclareNamespace("SharpJS.JSLibraries");
/* class SharpJS.JSLibraries.Ajax */ 

(function Ajax$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm04.SharpJS.JSLibraries.Ajax_AjaxResponseCallback)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm04.SharpJS.JSLibraries.JQuery.JQuery)) ();
  };


  function Ajax__ctor () {
  }; 

  function Ajax_Get$00 (url, callback) {
    $thisType.Get(url, "{}", callback);
  }; 

  function Ajax_Get$01 (url, data, callback) {
    $T02().get_JQueryStatic().get(url, data, callback, 'text');
  }; 

  function Ajax_Post$02 (url, callback) {
    $thisType.Post(url, "{}", callback);
  }; 

  function Ajax_Post$03 (url, data, callback) {
    $T02().get_JQueryStatic().get(url, data, callback, 'text');
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.Object"), 
      Name: "SharpJS.JSLibraries.Ajax", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      Ajax__ctor
    );

    $.Method({Static:true , Public:true }, "Get", 
      new JSIL.MethodSignature(null, [$.String, $asm04.TypeRef("SharpJS.JSLibraries.Ajax+AjaxResponseCallback")]), 
      Ajax_Get$00
    );

    $.Method({Static:true , Public:true }, "Get", 
      new JSIL.MethodSignature(null, [
          $.String, $.String, 
          $asm04.TypeRef("SharpJS.JSLibraries.Ajax+AjaxResponseCallback")
        ]), 
      Ajax_Get$01
    );

    $.Method({Static:true , Public:true }, "Post", 
      new JSIL.MethodSignature(null, [$.String, $asm04.TypeRef("SharpJS.JSLibraries.Ajax+AjaxResponseCallback")]), 
      Ajax_Post$02
    );

    $.Method({Static:true , Public:true }, "Post", 
      new JSIL.MethodSignature(null, [
          $.String, $.String, 
          $asm04.TypeRef("SharpJS.JSLibraries.Ajax+AjaxResponseCallback")
        ]), 
      Ajax_Post$03
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* delegate SharpJS.JSLibraries.Ajax+AjaxResponseCallback */ 

JSIL.MakeDelegate("SharpJS.JSLibraries.Ajax+AjaxResponseCallback", false, [], 
  new JSIL.MethodSignature(null, [
      $asm02.TypeRef("System.String"), $asm02.TypeRef("System.String"), 
      $asm02.TypeRef("System.Object")
    ]));

/* class SharpJS.JSLibraries.BufferConverter */ 

(function BufferConverter$Members () {
  var $, $thisType;

  function BufferConverter__ctor () {
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.Object"), 
      Name: "SharpJS.JSLibraries.BufferConverter", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      BufferConverter__ctor
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.JSLibraries.DocumentUtilities */ 

(function DocumentUtilities$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm03.SharpJS.Dom.Elements.LinkElement)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm04.SharpJS.JSLibraries.JQuery.JQuery)) ();
  };


  function DocumentUtilities__ctor () {
  }; 

  function DocumentUtilities_LoadExternalStylesheet (stylesheetPath) {
    var expr_05 = new ($T01())();
    expr_05.set_Href(stylesheetPath);
    expr_05.set_Type("text/css");
    expr_05.set_Relation("stylesheet");
    $T02().GetJQueryObject(expr_05);
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.Object"), 
      Name: "SharpJS.JSLibraries.DocumentUtilities", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      DocumentUtilities__ctor
    );

    $.Method({Static:true , Public:true }, "LoadExternalStylesheet", 
      JSIL.MethodSignature.Action($.String), 
      DocumentUtilities_LoadExternalStylesheet
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.JSLibraries.FileDownloader */ 

(function FileDownloader$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.Object)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm02.System.ArgumentNullException)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(new JSIL.ConstructorSignature($asm02.System.ArgumentNullException, [$asm02.System.String]))) ();
  };


  function FileDownloader_SaveJSBlobToFile (javaScriptBlob, filename) {
    if (javaScriptBlob === null) {
      throw $S00().Construct("javaScriptBlob");
    }
    if (filename === null) {
      throw $S00().Construct("filename");
    }
    saveAs(javaScriptBlob, filename);
  }; 

  function FileDownloader_SaveTextToFile (text, fileName) {
    if (text === null) {
      throw $S00().Construct("text");
    }
    if (fileName === null) {
      throw $S00().Construct("fileName");
    }
                    var blob = new Blob([text], { type: "text/plain;charset=utf-8"});
                    saveAs(blob, fileName);
  }; 

  JSIL.MakeStaticClass("SharpJS.JSLibraries.FileDownloader", true, [], function ($ib) {
    $ = $ib;

    $.Method({Static:true , Public:true }, "SaveJSBlobToFile", 
      new JSIL.MethodSignature(null, [$.Object, $.String]), 
      FileDownloader_SaveJSBlobToFile
    );

    $.Method({Static:true , Public:true }, "SaveTextToFile", 
      new JSIL.MethodSignature(null, [$.String, $.String]), 
      FileDownloader_SaveTextToFile
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.JSLibraries.PrintHelper */ 

(function PrintHelper$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };


  function PrintHelper_Print (elementToPrint) {
                        var printPreview = window.open('about:blank', 'print_preview', 'resizable=yes,scrollbars=yes,status=yes');
                        var printDocument = printPreview.document;
                        printDocument.open();
                        printDocument.write('<!DOCTYPE html>'+
                        '<html>'+
                            elementToPrint.get_InnerHtml().innerHTML+
                        '</html>');
                        printDocument.close();
                        printPreview.print();;
  }; 

  JSIL.MakeStaticClass("SharpJS.JSLibraries.PrintHelper", true, [], function ($ib) {
    $ = $ib;

    $.Method({Static:true , Public:true }, "Print", 
      JSIL.MethodSignature.Action($asm03.TypeRef("SharpJS.Dom.Element")), 
      PrintHelper_Print
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.JSLibraries.OnErrorEventArgs */ 

(function OnErrorEventArgs$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm02.System.EventArgs)) ();
  };


  function OnErrorEventArgs__ctor (data) {
    $T01().prototype._ctor.call(this);
    this.Data = data;
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.EventArgs"), 
      Name: "SharpJS.JSLibraries.OnErrorEventArgs", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 1, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Action($.String), 
      OnErrorEventArgs__ctor
    );

    $.Field({Static:false, Public:true , ReadOnly:true }, "Data", $.String);


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.JSLibraries.OnMessageEventArgs */ 

(function OnMessageEventArgs$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm02.System.EventArgs)) ();
  };


  function OnMessageEventArgs__ctor (data) {
    $T01().prototype._ctor.call(this);
    this.Data = data;
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.EventArgs"), 
      Name: "SharpJS.JSLibraries.OnMessageEventArgs", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 1, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Action($.String), 
      OnMessageEventArgs__ctor
    );

    $.Field({Static:false, Public:true , ReadOnly:true }, "Data", $.String);


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.JSLibraries.WebSocket */ 

(function WebSocket$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm02.System.Action$b1.Of($asm02.System.Object))) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm02.System.EventHandler)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm02.System.Delegate)) ();
  };
  var $T04 = function () {
    return ($T04 = JSIL.Memoize($asm02.System.Threading.Interlocked)) ();
  };
  var $T05 = function () {
    return ($T05 = JSIL.Memoize($asm02.System.EventHandler$b1.Of($asm04.SharpJS.JSLibraries.OnErrorEventArgs))) ();
  };
  var $T06 = function () {
    return ($T06 = JSIL.Memoize($asm02.System.EventHandler$b1.Of($asm04.SharpJS.JSLibraries.OnMessageEventArgs))) ();
  };
  var $T07 = function () {
    return ($T07 = JSIL.Memoize($asm02.System.Object)) ();
  };
  var $T08 = function () {
    return ($T08 = JSIL.Memoize($asm02.System.EventArgs)) ();
  };
  var $T09 = function () {
    return ($T09 = JSIL.Memoize($asm02.System.Convert)) ();
  };
  var $T0A = function () {
    return ($T0A = JSIL.Memoize($asm04.SharpJS.JSLibraries.OnErrorEventArgs)) ();
  };
  var $T0B = function () {
    return ($T0B = JSIL.Memoize($asm04.SharpJS.JSLibraries.OnMessageEventArgs)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.Object")))) ();
  };
  var $S01 = function () {
    return ($S01 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.Object")))) ();
  };
  var $S02 = function () {
    return ($S02 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.Object")))) ();
  };
  var $S03 = function () {
    return ($S03 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.Object")))) ();
  };
  var $S04 = function () {
    return ($S04 = JSIL.Memoize(new JSIL.MethodSignature($asm02.System.String, [$asm02.System.Object]))) ();
  };


  function WebSocket__ctor (uri) {
    this._webSocketObjectHandle = (new WebSocket(uri));
    this._webSocketObjectHandle.onopen = $T01().New(this, null, new JSIL.MethodPointerInfo($thisType, "OnOpenCallback", $S00(), false, false));
                          this._webSocketObjectHandle.onclose = $T01().New(this, null, new JSIL.MethodPointerInfo($thisType, "OnCloseCallback", $S01(), false, false));
                          this._webSocketObjectHandle.onmessage = $T01().New(this, null, new JSIL.MethodPointerInfo($thisType, "OnMessageCallback", $S02(), false, false));
                          this._webSocketObjectHandle.onerror = $T01().New(this, null, new JSIL.MethodPointerInfo($thisType, "OnErrorCallback", $S03(), false, false));
  }; 

  function WebSocket_add_OnClose (value) {
    var eventHandler = this.OnClose;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T03().Combine(eventHandler2, value);
      eventHandler = $T04().CompareExchange$b1($T02())(/* ref */ new JSIL.MemberReference(this, "OnClose"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function WebSocket_add_OnError (value) {
    var eventHandler = this.OnError;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T03().Combine(eventHandler2, value);
      eventHandler = $T04().CompareExchange$b1($T05())(/* ref */ new JSIL.MemberReference(this, "OnError"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function WebSocket_add_OnMessage (value) {
    var eventHandler = this.OnMessage;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T03().Combine(eventHandler2, value);
      eventHandler = $T04().CompareExchange$b1($T06())(/* ref */ new JSIL.MemberReference(this, "OnMessage"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function WebSocket_add_OnOpen (value) {
    var eventHandler = this.OnOpen;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T03().Combine(eventHandler2, value);
      eventHandler = $T04().CompareExchange$b1($T02())(/* ref */ new JSIL.MemberReference(this, "OnOpen"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function WebSocket_Close () {
    this._webSocketObjectHandle.close();
  }; 

  function WebSocket_OnCloseCallback (e) {
    if (this.OnClose !== null) {
      this.OnClose(this, new ($T08())());
    }
  }; 

  function WebSocket_OnErrorCallback (e) {
    var data = $S04().CallStatic($T09(), "ToString", null, e.data);
    if (this.OnError !== null) {
      this.OnError(this, new ($T0A())(data));
    }
  }; 

  function WebSocket_OnMessageCallback (e) {
    var data = $S04().CallStatic($T09(), "ToString", null, e.data);
    if (this.OnMessage !== null) {
      this.OnMessage(this, new ($T0B())(data));
    }
  }; 

  function WebSocket_OnOpenCallback (e) {
    if (this.OnOpen !== null) {
      this.OnOpen(this, new ($T08())());
    }
  }; 

  function WebSocket_remove_OnClose (value) {
    var eventHandler = this.OnClose;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T03().Remove(eventHandler2, value);
      eventHandler = $T04().CompareExchange$b1($T02())(/* ref */ new JSIL.MemberReference(this, "OnClose"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function WebSocket_remove_OnError (value) {
    var eventHandler = this.OnError;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T03().Remove(eventHandler2, value);
      eventHandler = $T04().CompareExchange$b1($T05())(/* ref */ new JSIL.MemberReference(this, "OnError"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function WebSocket_remove_OnMessage (value) {
    var eventHandler = this.OnMessage;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T03().Remove(eventHandler2, value);
      eventHandler = $T04().CompareExchange$b1($T06())(/* ref */ new JSIL.MemberReference(this, "OnMessage"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function WebSocket_remove_OnOpen (value) {
    var eventHandler = this.OnOpen;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T03().Remove(eventHandler2, value);
      eventHandler = $T04().CompareExchange$b1($T02())(/* ref */ new JSIL.MemberReference(this, "OnOpen"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function WebSocket_Send (message) {
    this._webSocketObjectHandle.send(message);
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.Object"), 
      Name: "SharpJS.JSLibraries.WebSocket", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 1, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Action($.String), 
      WebSocket__ctor
    );

    $.Method({Static:false, Public:true }, "add_OnClose", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      WebSocket_add_OnClose
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "add_OnError", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler`1", [$asm04.TypeRef("SharpJS.JSLibraries.OnErrorEventArgs")])), 
      WebSocket_add_OnError
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "add_OnMessage", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler`1", [$asm04.TypeRef("SharpJS.JSLibraries.OnMessageEventArgs")])), 
      WebSocket_add_OnMessage
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "add_OnOpen", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      WebSocket_add_OnOpen
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "Close", 
      JSIL.MethodSignature.Void, 
      WebSocket_Close
    );

    $.Method({Static:false, Public:false}, "OnCloseCallback", 
      JSIL.MethodSignature.Action($.Object), 
      WebSocket_OnCloseCallback
    );

    $.Method({Static:false, Public:false}, "OnErrorCallback", 
      JSIL.MethodSignature.Action($.Object), 
      WebSocket_OnErrorCallback
    );

    $.Method({Static:false, Public:false}, "OnMessageCallback", 
      JSIL.MethodSignature.Action($.Object), 
      WebSocket_OnMessageCallback
    );

    $.Method({Static:false, Public:false}, "OnOpenCallback", 
      JSIL.MethodSignature.Action($.Object), 
      WebSocket_OnOpenCallback
    );

    $.Method({Static:false, Public:true }, "remove_OnClose", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      WebSocket_remove_OnClose
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "remove_OnError", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler`1", [$asm04.TypeRef("SharpJS.JSLibraries.OnErrorEventArgs")])), 
      WebSocket_remove_OnError
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "remove_OnMessage", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler`1", [$asm04.TypeRef("SharpJS.JSLibraries.OnMessageEventArgs")])), 
      WebSocket_remove_OnMessage
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "remove_OnOpen", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      WebSocket_remove_OnOpen
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "Send", 
      JSIL.MethodSignature.Action($.String), 
      WebSocket_Send
    );

    $.Field({Static:false, Public:false, ReadOnly:true }, "_webSocketObjectHandle", $.Object);

    $.Field({Static:false, Public:false}, "OnClose", $asm02.TypeRef("System.EventHandler"))
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Field({Static:false, Public:false}, "OnError", $asm02.TypeRef("System.EventHandler`1", [$asm04.TypeRef("SharpJS.JSLibraries.OnErrorEventArgs")]))
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Field({Static:false, Public:false}, "OnMessage", $asm02.TypeRef("System.EventHandler`1", [$asm04.TypeRef("SharpJS.JSLibraries.OnMessageEventArgs")]))
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Field({Static:false, Public:false}, "OnOpen", $asm02.TypeRef("System.EventHandler"))
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Event({Static:false, Public:true }, "OnClose", $asm02.TypeRef("System.EventHandler"));

    $.Event({Static:false, Public:true }, "OnError", $asm02.TypeRef("System.EventHandler`1", [$asm04.TypeRef("SharpJS.JSLibraries.OnErrorEventArgs")]));

    $.Event({Static:false, Public:true }, "OnMessage", $asm02.TypeRef("System.EventHandler`1", [$asm04.TypeRef("SharpJS.JSLibraries.OnMessageEventArgs")]));

    $.Event({Static:false, Public:true }, "OnOpen", $asm02.TypeRef("System.EventHandler"));


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

JSIL.DeclareNamespace("SharpJS.JSLibraries.JQuery");
/* class SharpJS.JSLibraries.JQuery.JQElement */ 

(function JQElement$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm04.SharpJS.JSLibraries.JQuery.JQuery)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm02.System.Object)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm02.System.EventHandler)) ();
  };
  var $T04 = function () {
    return ($T04 = JSIL.Memoize($asm02.System.EventArgs)) ();
  };
  var $T05 = function () {
    return ($T05 = JSIL.Memoize($asm02.System.Delegate)) ();
  };
  var $T06 = function () {
    return ($T06 = JSIL.Memoize($asm02.System.Threading.Interlocked)) ();
  };
  var $T07 = function () {
    return ($T07 = JSIL.Memoize($asm02.System.Action$b1.Of($asm02.System.Object))) ();
  };
  var $T08 = function () {
    return ($T08 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $T09 = function () {
    return ($T09 = JSIL.Memoize($asm04.SharpJS.JSLibraries.JQuery.JQueryObject)) ();
  };
  var $T0A = function () {
    return ($T0A = JSIL.Memoize($asm02.System.Type)) ();
  };
  var $T0B = function () {
    return ($T0B = JSIL.Memoize($asm02.System.Action$b1)) ();
  };
  var $T0C = function () {
    return ($T0C = JSIL.Memoize($asm02.System.Int32)) ();
  };
  var $T0D = function () {
    return ($T0D = JSIL.Memoize($asm02.System.Action)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.Object")))) ();
  };
  var $S01 = function () {
    return ($S01 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.Object")))) ();
  };
  var $S02 = function () {
    return ($S02 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.Object")))) ();
  };
  var $S03 = function () {
    return ($S03 = JSIL.Memoize(JSIL.MethodSignature.Action($asm02.TypeRef("System.Object")))) ();
  };
  var $S04 = function () {
    return ($S04 = JSIL.Memoize(new JSIL.MethodSignature("!!0", [$asm02.System.String], ["T"]))) ();
  };


  function JQElement__ctor (element) {
    this.JQElement$JQueryObjectHandle$value = $T01().GetJQueryObject(element);
  }; 

  function JQElement_$ladd_Click$gb__8_0 (e) {
    var expr_06 = this._click;
    if (expr_06 === null) {
      return;
    }
    expr_06(this, new ($T04())());
  }; 

  function JQElement_$ladd_EnterKeyPressed$gb__11_0 (e) {
    var expr_06 = this._enterKeyPressed;
    if (expr_06 === null) {
      return;
    }
    expr_06(this, new ($T04())());
  }; 

  function JQElement_$ladd_Focus$gb__14_0 (e) {
    var expr_06 = this._focus;
    if (expr_06 === null) {
      return;
    }
    expr_06(this, new ($T04())());
  }; 

  function JQElement_$ladd_LostFocus$gb__17_0 (e) {
    var expr_06 = this._focusout;
    if (expr_06 === null) {
      return;
    }
    expr_06(this, new ($T04())());
  }; 

  function JQElement_add__click (value) {
    var eventHandler = this._click;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T05().Combine(eventHandler2, value);
      eventHandler = $T06().CompareExchange$b1($T03())(/* ref */ new JSIL.MemberReference(this, "_click"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function JQElement_add__enterKeyPressed (value) {
    var eventHandler = this._enterKeyPressed;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T05().Combine(eventHandler2, value);
      eventHandler = $T06().CompareExchange$b1($T03())(/* ref */ new JSIL.MemberReference(this, "_enterKeyPressed"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function JQElement_add__focus (value) {
    var eventHandler = this._focus;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T05().Combine(eventHandler2, value);
      eventHandler = $T06().CompareExchange$b1($T03())(/* ref */ new JSIL.MemberReference(this, "_focus"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function JQElement_add__focusout (value) {
    var eventHandler = this._focusout;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T05().Combine(eventHandler2, value);
      eventHandler = $T06().CompareExchange$b1($T03())(/* ref */ new JSIL.MemberReference(this, "_focusout"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function JQElement_add_Click (value) {
    this.BindEventListener("click", $T07().New(this, null, new JSIL.MethodPointerInfo($thisType, "$ladd_Click$gb__8_0", $S00(), false, false)));
    this.add__click(value);
  }; 

  function JQElement_add_EnterKeyPressed (value) {
    this.BindEventListener("change", $T07().New(this, null, new JSIL.MethodPointerInfo($thisType, "$ladd_EnterKeyPressed$gb__11_0", $S01(), false, false)));
    this.add__enterKeyPressed(value);
  }; 

  function JQElement_add_Focus (value) {
    this.BindEventListener("focus", $T07().New(this, null, new JSIL.MethodPointerInfo($thisType, "$ladd_Focus$gb__14_0", $S02(), false, false)));
    this.add__focus(value);
  }; 

  function JQElement_add_LostFocus (value) {
    this.BindEventListener("focusout", $T07().New(this, null, new JSIL.MethodPointerInfo($thisType, "$ladd_LostFocus$gb__17_0", $S03(), false, false)));
    this.add__focusout(value);
  }; 

  function JQElement_AddClass (className) {
    this.JQElement$JQueryObjectHandle$value.JQObject.addClass(className);
  }; 

  function JQElement_Append$00 (elementHtml) {
    this.JQElement$JQueryObjectHandle$value.JQObject.append(elementHtml);
  }; 

  function JQElement_Append$01 (jqElement) {
    this.JQElement$JQueryObjectHandle$value.JQObject.append(jqElement.JQueryObjectHandle.JQObject);
  }; 

  function JQElement_Append$02 (element) {
    this.JQElement$JQueryObjectHandle$value.JQObject.append(element.DOMRepresentation);
  }; 

  function JQElement_AppendTo$03 (elementHtml) {
    this.JQElement$JQueryObjectHandle$value.JQObject.appendTo(elementHtml);
  }; 

  function JQElement_AppendTo$04 (jqElement) {
    this.JQElement$JQueryObjectHandle$value.JQObject.appendTo(jqElement.JQueryObjectHandle.JQObject);
  }; 

  function JQElement_AppendTo$05 (element) {
    this.JQElement$JQueryObjectHandle$value.JQObject.appendTo(element.DOMRepresentation);
  }; 

  function JQElement_Attr$06 (name) {
    return this.JQElement$JQueryObjectHandle$value.JQObject.attr(name);
  }; 

  function JQElement_Attr$b1$07 (T, name) {
    return this.JQElement$JQueryObjectHandle$value.JQObject.attr(name);
  }; 

  function JQElement_Attr$08 (name, value) {
    this.JQElement$JQueryObjectHandle$value.JQObject.attr(name, value);
  }; 

  function JQElement_Attr$b1$09 (T, name, value) {
    this.JQElement$JQueryObjectHandle$value.JQObject.attr(name, value);
  }; 

  function JQElement_BindEventListener (eventName, handler) {
    this.JQElement$JQueryObjectHandle$value.JQObject.on(eventName, handler);
  }; 

  function JQElement_Contents () {
    return this.JQElement$JQueryObjectHandle$value.JQObject.contents();
  }; 

  function JQElement_Css (name, value) {
    this.JQElement$JQueryObjectHandle$value.JQObject.css(name, value);
  }; 

  function JQElement_Css$b1$0A (T, name, value) {
    this.JQElement$JQueryObjectHandle$value.JQObject.css(name, value);
  }; 

  function JQElement_Css$b1$0B (T, name) {
    return $S04().CallVirtual("Css$b1", [T], this.JQElement$JQueryObjectHandle$value, name);
  }; 

  function JQElement_Draggable () {
    this.JQElement$JQueryObjectHandle$value.JQObject.draggable();
  }; 

  function JQElement_FadeIn$0C () {
    this.JQElement$JQueryObjectHandle$value.JQObject.fadeIn();
  }; 

  function JQElement_FadeIn$0D (timeout) {
    this.JQElement$JQueryObjectHandle$value.JQObject.fadeIn(timeout);
  }; 

  function JQElement_FadeIn$0E (timeout, finishedCallback) {
    this.JQElement$JQueryObjectHandle$value.JQObject.fadeIn(timeout, finishedCallback);
  }; 

  function JQElement_FadeOut$0F () {
    this.JQElement$JQueryObjectHandle$value.JQObject.fadeOut();
  }; 

  function JQElement_FadeOut$10 (timeout) {
    this.JQElement$JQueryObjectHandle$value.JQObject.fadeOut(timeout);
  }; 

  function JQElement_FadeOut$11 (timeout, finishedCallback) {
    this.JQElement$JQueryObjectHandle$value.JQObject.fadeOut(timeout, finishedCallback);
  }; 

  function JQElement_Find (selector) {
    return this.JQElement$JQueryObjectHandle$value.JQObject.find(selector);
  }; 

  function JQElement_get_DomRepresentation () {
    return (this.JQElement$JQueryObjectHandle$value).get_DomRepresentation();
  }; 

  function JQElement_get_JQueryObjectHandle () {
    return this.JQElement$JQueryObjectHandle$value;
  }; 

  function JQElement_Height$12 (value) {
    this.JQElement$JQueryObjectHandle$value.JQObject.height(value);
  }; 

  function JQElement_Height$13 () {
    return this.JQElement$JQueryObjectHandle$value.JQObject.height();
  }; 

  function JQElement_Hide () {
    this.JQElement$JQueryObjectHandle$value.JQObject.hide();
  }; 

  function JQElement_Html$14 (htmlString) {
    this.JQElement$JQueryObjectHandle$value.JQObject.html(htmlString);
  }; 

  function JQElement_Html$15 () {
    return this.JQElement$JQueryObjectHandle$value.JQObject.html();
  }; 

  function JQElement_Is (query) {
    return this.JQElement$JQueryObjectHandle$value.JQObject.is(query);
  }; 

  function JQElement_Remove () {
    this.JQElement$JQueryObjectHandle$value.JQObject.remove();
  }; 

  function JQElement_remove__click (value) {
    var eventHandler = this._click;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T05().Remove(eventHandler2, value);
      eventHandler = $T06().CompareExchange$b1($T03())(/* ref */ new JSIL.MemberReference(this, "_click"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function JQElement_remove__enterKeyPressed (value) {
    var eventHandler = this._enterKeyPressed;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T05().Remove(eventHandler2, value);
      eventHandler = $T06().CompareExchange$b1($T03())(/* ref */ new JSIL.MemberReference(this, "_enterKeyPressed"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function JQElement_remove__focus (value) {
    var eventHandler = this._focus;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T05().Remove(eventHandler2, value);
      eventHandler = $T06().CompareExchange$b1($T03())(/* ref */ new JSIL.MemberReference(this, "_focus"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function JQElement_remove__focusout (value) {
    var eventHandler = this._focusout;

    do {
      var eventHandler2 = eventHandler;
      var value2 = $T05().Remove(eventHandler2, value);
      eventHandler = $T06().CompareExchange$b1($T03())(/* ref */ new JSIL.MemberReference(this, "_focusout"), value2, eventHandler2);
    } while (eventHandler !== eventHandler2);
  }; 

  function JQElement_remove_Click (value) {
    this.UnbindEventListener("click");
    this.remove__click(value);
  }; 

  function JQElement_remove_EnterKeyPressed (value) {
    this.UnbindEventListener("change");
    this.remove__enterKeyPressed(value);
  }; 

  function JQElement_remove_Focus (value) {
    this.UnbindEventListener("focus");
    this.remove__focus(value);
  }; 

  function JQElement_remove_LostFocus (value) {
    this.UnbindEventListener("focusout");
    this.remove__focusout(value);
  }; 

  function JQElement_RemoveClass (className) {
    this.JQElement$JQueryObjectHandle$value.JQObject.removeClass(className);
  }; 

  function JQElement_Resizable () {
    this.JQElement$JQueryObjectHandle$value.JQObject.resizable();
  }; 

  function JQElement_ResizableAnimated () {
    this.JQElement$JQueryObjectHandle$value.JQObject.resizable({animate: true});
  }; 

  function JQElement_set_JQueryObjectHandle (value) {
    this.JQElement$JQueryObjectHandle$value = value;
  }; 

  function JQElement_Show () {
    this.JQElement$JQueryObjectHandle$value.JQObject.show();
  }; 

  function JQElement_Trigger (eventName) {
    this.JQElement$JQueryObjectHandle$value.JQObject.trigger(eventName);
  }; 

  function JQElement_UnbindEventListener (eventName) {
    this.JQElement$JQueryObjectHandle$value.JQObject.off(eventName);
  }; 

  function JQElement_Width$16 () {
    return this.JQElement$JQueryObjectHandle$value.JQObject.width();
  }; 

  function JQElement_Width$17 (value) {
    this.JQElement$JQueryObjectHandle$value.JQObject.width(value);
  }; 

  function JQElement_ZIndex$18 () {
    return this.JQElement$JQueryObjectHandle$value.JQObject.zIndex();
  }; 

  function JQElement_ZIndex$19 (value) {
    this.JQElement$JQueryObjectHandle$value.JQObject.zIndex(value);
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.Object"), 
      Name: "SharpJS.JSLibraries.JQuery.JQElement", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 1, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Action($asm03.TypeRef("SharpJS.Dom.Element")), 
      JQElement__ctor
    );

    $.Method({Static:false, Public:false}, "$ladd_Click$gb__8_0", 
      JSIL.MethodSignature.Action($.Object), 
      JQElement_$ladd_Click$gb__8_0
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "$ladd_EnterKeyPressed$gb__11_0", 
      JSIL.MethodSignature.Action($.Object), 
      JQElement_$ladd_EnterKeyPressed$gb__11_0
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "$ladd_Focus$gb__14_0", 
      JSIL.MethodSignature.Action($.Object), 
      JQElement_$ladd_Focus$gb__14_0
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "$ladd_LostFocus$gb__17_0", 
      JSIL.MethodSignature.Action($.Object), 
      JQElement_$ladd_LostFocus$gb__17_0
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "add__click", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      JQElement_add__click
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "add__enterKeyPressed", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      JQElement_add__enterKeyPressed
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "add__focus", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      JQElement_add__focus
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "add__focusout", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      JQElement_add__focusout
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "add_Click", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      JQElement_add_Click
    );

    $.Method({Static:false, Public:true }, "add_EnterKeyPressed", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      JQElement_add_EnterKeyPressed
    );

    $.Method({Static:false, Public:true }, "add_Focus", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      JQElement_add_Focus
    );

    $.Method({Static:false, Public:true }, "add_LostFocus", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      JQElement_add_LostFocus
    );

    $.Method({Static:false, Public:true }, "AddClass", 
      JSIL.MethodSignature.Action($.String), 
      JQElement_AddClass
    );

    $.Method({Static:false, Public:true }, "Append", 
      JSIL.MethodSignature.Action($.String), 
      JQElement_Append$00
    );

    $.Method({Static:false, Public:true }, "Append", 
      JSIL.MethodSignature.Action($.Type), 
      JQElement_Append$01
    );

    $.Method({Static:false, Public:true }, "Append", 
      JSIL.MethodSignature.Action($asm03.TypeRef("SharpJS.Dom.Element")), 
      JQElement_Append$02
    );

    $.Method({Static:false, Public:true }, "AppendTo", 
      JSIL.MethodSignature.Action($.String), 
      JQElement_AppendTo$03
    );

    $.Method({Static:false, Public:true }, "AppendTo", 
      JSIL.MethodSignature.Action($.Type), 
      JQElement_AppendTo$04
    );

    $.Method({Static:false, Public:true }, "AppendTo", 
      JSIL.MethodSignature.Action($asm03.TypeRef("SharpJS.Dom.Element")), 
      JQElement_AppendTo$05
    );

    $.Method({Static:false, Public:true }, "Attr", 
      new JSIL.MethodSignature($.String, [$.String]), 
      JQElement_Attr$06
    );

    $.Method({Static:false, Public:true }, "Attr", 
      new JSIL.MethodSignature("!!0", [$.String], ["T"]), 
      JQElement_Attr$b1$07
    );

    $.Method({Static:false, Public:true }, "Attr", 
      new JSIL.MethodSignature(null, [$.String, $.String]), 
      JQElement_Attr$08
    );

    $.Method({Static:false, Public:true }, "Attr", 
      new JSIL.MethodSignature(null, [$.String, "!!0"], ["T"]), 
      JQElement_Attr$b1$09
    );

    $.Method({Static:false, Public:true }, "BindEventListener", 
      new JSIL.MethodSignature(null, [$.String, $asm02.TypeRef("System.Action`1", [$.Object])]), 
      JQElement_BindEventListener
    );

    $.Method({Static:false, Public:true }, "Contents", 
      JSIL.MethodSignature.Return($.Object), 
      JQElement_Contents
    );

    $.Method({Static:false, Public:true }, "Css", 
      new JSIL.MethodSignature(null, [$.String, $.String]), 
      JQElement_Css
    );

    $.Method({Static:false, Public:true }, "Css", 
      new JSIL.MethodSignature(null, [$.String, "!!0"], ["T"]), 
      JQElement_Css$b1$0A
    );

    $.Method({Static:false, Public:true }, "Css", 
      new JSIL.MethodSignature("!!0", [$.String], ["T"]), 
      JQElement_Css$b1$0B
    );

    $.Method({Static:false, Public:true }, "Draggable", 
      JSIL.MethodSignature.Void, 
      JQElement_Draggable
    );

    $.Method({Static:false, Public:true }, "FadeIn", 
      JSIL.MethodSignature.Void, 
      JQElement_FadeIn$0C
    );

    $.Method({Static:false, Public:true }, "FadeIn", 
      JSIL.MethodSignature.Action($.Int32), 
      JQElement_FadeIn$0D
    );

    $.Method({Static:false, Public:true }, "FadeIn", 
      new JSIL.MethodSignature(null, [$.Int32, $asm02.TypeRef("System.Action")]), 
      JQElement_FadeIn$0E
    );

    $.Method({Static:false, Public:true }, "FadeOut", 
      JSIL.MethodSignature.Void, 
      JQElement_FadeOut$0F
    );

    $.Method({Static:false, Public:true }, "FadeOut", 
      JSIL.MethodSignature.Action($.Int32), 
      JQElement_FadeOut$10
    );

    $.Method({Static:false, Public:true }, "FadeOut", 
      new JSIL.MethodSignature(null, [$.Int32, $asm02.TypeRef("System.Action")]), 
      JQElement_FadeOut$11
    );

    $.Method({Static:false, Public:true }, "Find", 
      new JSIL.MethodSignature($.Object, [$.String]), 
      JQElement_Find
    );

    $.Method({Static:false, Public:true }, "get_DomRepresentation", 
      JSIL.MethodSignature.Return($asm03.TypeRef("SharpJS.Dom.Element")), 
      JQElement_get_DomRepresentation
    );

    $.Method({Static:false, Public:true }, "get_JQueryObjectHandle", 
      JSIL.MethodSignature.Return($asm04.TypeRef("SharpJS.JSLibraries.JQuery.JQueryObject")), 
      JQElement_get_JQueryObjectHandle
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "Height", 
      JSIL.MethodSignature.Action($.Int32), 
      JQElement_Height$12
    );

    $.Method({Static:false, Public:true }, "Height", 
      JSIL.MethodSignature.Return($.Int32), 
      JQElement_Height$13
    );

    $.Method({Static:false, Public:true }, "Hide", 
      JSIL.MethodSignature.Void, 
      JQElement_Hide
    );

    $.Method({Static:false, Public:true }, "Html", 
      JSIL.MethodSignature.Action($.String), 
      JQElement_Html$14
    );

    $.Method({Static:false, Public:true }, "Html", 
      JSIL.MethodSignature.Return($.String), 
      JQElement_Html$15
    );

    $.Method({Static:false, Public:true }, "Is", 
      new JSIL.MethodSignature($.Boolean, [$.String]), 
      JQElement_Is
    );

    $.Method({Static:false, Public:true }, "Remove", 
      JSIL.MethodSignature.Void, 
      JQElement_Remove
    );

    $.Method({Static:false, Public:false}, "remove__click", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      JQElement_remove__click
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "remove__enterKeyPressed", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      JQElement_remove__enterKeyPressed
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "remove__focus", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      JQElement_remove__focus
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "remove__focusout", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      JQElement_remove__focusout
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "remove_Click", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      JQElement_remove_Click
    );

    $.Method({Static:false, Public:true }, "remove_EnterKeyPressed", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      JQElement_remove_EnterKeyPressed
    );

    $.Method({Static:false, Public:true }, "remove_Focus", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      JQElement_remove_Focus
    );

    $.Method({Static:false, Public:true }, "remove_LostFocus", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.EventHandler")), 
      JQElement_remove_LostFocus
    );

    $.Method({Static:false, Public:true }, "RemoveClass", 
      JSIL.MethodSignature.Action($.String), 
      JQElement_RemoveClass
    );

    $.Method({Static:false, Public:true }, "Resizable", 
      JSIL.MethodSignature.Void, 
      JQElement_Resizable
    );

    $.Method({Static:false, Public:true }, "ResizableAnimated", 
      JSIL.MethodSignature.Void, 
      JQElement_ResizableAnimated
    );

    $.Method({Static:false, Public:true }, "set_JQueryObjectHandle", 
      JSIL.MethodSignature.Action($asm04.TypeRef("SharpJS.JSLibraries.JQuery.JQueryObject")), 
      JQElement_set_JQueryObjectHandle
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "Show", 
      JSIL.MethodSignature.Void, 
      JQElement_Show
    );

    $.Method({Static:false, Public:true }, "Trigger", 
      JSIL.MethodSignature.Action($.String), 
      JQElement_Trigger
    );

    $.Method({Static:false, Public:true }, "UnbindEventListener", 
      JSIL.MethodSignature.Action($.String), 
      JQElement_UnbindEventListener
    );

    $.Method({Static:false, Public:true }, "Width", 
      JSIL.MethodSignature.Return($.Int32), 
      JQElement_Width$16
    );

    $.Method({Static:false, Public:true }, "Width", 
      JSIL.MethodSignature.Action($.Int32), 
      JQElement_Width$17
    );

    $.Method({Static:false, Public:true }, "ZIndex", 
      JSIL.MethodSignature.Return($.Int32), 
      JQElement_ZIndex$18
    );

    $.Method({Static:false, Public:true }, "ZIndex", 
      JSIL.MethodSignature.Action($.Int32), 
      JQElement_ZIndex$19
    );

    $.Field({Static:false, Public:false}, "JQElement$JQueryObjectHandle$value", $asm04.TypeRef("SharpJS.JSLibraries.JQuery.JQueryObject"))
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Field({Static:false, Public:false}, "_click", $asm02.TypeRef("System.EventHandler"))
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Field({Static:false, Public:false}, "_enterKeyPressed", $asm02.TypeRef("System.EventHandler"))
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Field({Static:false, Public:false}, "_focus", $asm02.TypeRef("System.EventHandler"))
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Field({Static:false, Public:false}, "_focusout", $asm02.TypeRef("System.EventHandler"))
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Property({Static:false, Public:true }, "DomRepresentation", $asm03.TypeRef("SharpJS.Dom.Element"));

    $.Property({Static:false, Public:true }, "JQueryObjectHandle", $asm04.TypeRef("SharpJS.JSLibraries.JQuery.JQueryObject"));

    $.Event({Static:false, Public:true }, "Click", $asm02.TypeRef("System.EventHandler"));

    $.Event({Static:false, Public:true }, "EnterKeyPressed", $asm02.TypeRef("System.EventHandler"));

    $.Event({Static:false, Public:true }, "Focus", $asm02.TypeRef("System.EventHandler"));

    $.Event({Static:false, Public:true }, "LostFocus", $asm02.TypeRef("System.EventHandler"));

    $.Event({Static:false, Public:false}, "_click", $asm02.TypeRef("System.EventHandler"));

    $.Event({Static:false, Public:false}, "_enterKeyPressed", $asm02.TypeRef("System.EventHandler"));

    $.Event({Static:false, Public:false}, "_focus", $asm02.TypeRef("System.EventHandler"));

    $.Event({Static:false, Public:false}, "_focusout", $asm02.TypeRef("System.EventHandler"));


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.JSLibraries.JQuery.JQuery */ 

(function JQuery$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize(System.Array.Of($asm02.System.Object))) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm02.System.Object)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm04.SharpJS.JSLibraries.JQuery.JQueryObject)) ();
  };
  var $T04 = function () {
    return ($T04 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $T05 = function () {
    return ($T05 = JSIL.Memoize($asm02.System.InvalidOperationException)) ();
  };
  var $T06 = function () {
    return ($T06 = JSIL.Memoize($asm02.System.Boolean)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(new JSIL.ConstructorSignature($asm02.System.InvalidOperationException, [$asm02.System.String]))) ();
  };


  function JQuery_DynamicInvoke (methodName, parameters) {
    $thisType._jq[methodName];
    return null.apply(parameters, /* Expansion '2' not found */ null);
  }; 

  function JQuery_FromSelector (selector) {
    return new ($T03())($thisType._jq(/* Expansion 'rawDoMobject' not found */ null));
  }; 

  function JQuery_get_IsInitialized () {
    return $thisType.JQuery$IsInitialized$value;
  }; 

  function JQuery_get_JQueryStatic () {
    return $thisType._jq;
  }; 

  function JQuery_GetJQueryObject (element) {
    return new ($T03())($thisType._jq(element.get_DOMRepresentation()));
  }; 

  function JQuery_Initialize () {
    var expr_0A = (jQuery.noConflict(true));
    if (expr_0A === null) {
      throw $S00().Construct("Cannot use jQuery with SharpJS if the jQuery library has not been loaded.");
    }
    $thisType.JQuery$IsInitialized$value = true;
    $thisType._jq = expr_0A;
  }; 

  function JQuery_set_IsInitialized (value) {
    $thisType.JQuery$IsInitialized$value = value;
  }; 

  function JQuery_set_JQueryStatic (value) {
    $thisType._jq = value;
  }; 

  JSIL.MakeStaticClass("SharpJS.JSLibraries.JQuery.JQuery", true, [], function ($ib) {
    $ = $ib;

    $.Method({Static:true , Public:true }, "DynamicInvoke", 
      new JSIL.MethodSignature($.Object, [$.String, $jsilcore.TypeRef("System.Array", [$.Object])]), 
      JQuery_DynamicInvoke
    )
      .Parameter(1, "parameters", function (_) {
          _.Attribute($asm02.TypeRef("System.ParamArrayAttribute"))
        });

    $.Method({Static:true , Public:true }, "FromSelector", 
      new JSIL.MethodSignature($asm04.TypeRef("SharpJS.JSLibraries.JQuery.JQueryObject"), [$.String]), 
      JQuery_FromSelector
    );

    $.Method({Static:true , Public:true }, "get_IsInitialized", 
      JSIL.MethodSignature.Return($.Boolean), 
      JQuery_get_IsInitialized
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:true , Public:true }, "get_JQueryStatic", 
      JSIL.MethodSignature.Return($.Object), 
      JQuery_get_JQueryStatic
    );

    $.Method({Static:true , Public:true }, "GetJQueryObject", 
      new JSIL.MethodSignature($asm04.TypeRef("SharpJS.JSLibraries.JQuery.JQueryObject"), [$asm03.TypeRef("SharpJS.Dom.Element")]), 
      JQuery_GetJQueryObject
    );

    $.Method({Static:true , Public:true }, "Initialize", 
      JSIL.MethodSignature.Void, 
      JQuery_Initialize
    );

    $.Method({Static:true , Public:false}, "set_IsInitialized", 
      JSIL.MethodSignature.Action($.Boolean), 
      JQuery_set_IsInitialized
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:true , Public:true }, "set_JQueryStatic", 
      JSIL.MethodSignature.Action($.Object), 
      JQuery_set_JQueryStatic
    );

    $.Field({Static:true , Public:false}, "_jq", $.Object);

    $.Field({Static:true , Public:false}, "JQuery$IsInitialized$value", $.Boolean)
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));


    function JQuery__cctor () {
      $thisType.Initialize();
    }; 

    $.Method({Static:true , Public:false}, ".cctor", 
      JSIL.MethodSignature.Void, 
      JQuery__cctor
    );

    $.Property({Static:true , Public:true }, "IsInitialized", $.Boolean);

    $.Property({Static:true , Public:true }, "JQueryStatic", $.Object);


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SharpJS.JSLibraries.JQuery.JQueryObject */ 

(function JQueryObject$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.Object)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm02.System.Type)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm02.System.String)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(new JSIL.ConstructorSignature($asm03.SharpJS.Dom.Element, [$asm02.System.Object]))) ();
  };


  function JQueryObject__ctor (handle) {
    this.JQueryObject$JQObject$value = handle;
  }; 

  function JQueryObject_Css$b1$00 (T, name) {
    return T.$Cast(this.JQObject.css(name));
  }; 

  function JQueryObject_get_DomRepresentation () {
    return $S00().Construct(this.JQObject[0]);
  }; 

  function JQueryObject_get_JQObject () {
    return this.JQueryObject$JQObject$value;
  }; 

  function JQueryObject_set_JQObject (value) {
    this.JQueryObject$JQObject$value = value;
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.Object"), 
      Name: "SharpJS.JSLibraries.JQuery.JQueryObject", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 1, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:false}, ".ctor", 
      JSIL.MethodSignature.Action($.Object), 
      JQueryObject__ctor
    );

    $.Method({Static:false, Public:true }, "Css", 
      new JSIL.MethodSignature("!!0", [$.String], ["T"]), 
      JQueryObject_Css$b1$00
    );

    $.Method({Static:false, Public:true }, "get_DomRepresentation", 
      JSIL.MethodSignature.Return($asm03.TypeRef("SharpJS.Dom.Element")), 
      JQueryObject_get_DomRepresentation
    );

    $.Method({Static:false, Public:true }, "get_JQObject", 
      JSIL.MethodSignature.Return($.Object), 
      JQueryObject_get_JQObject
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_JQObject", 
      JSIL.MethodSignature.Action($.Object), 
      JQueryObject_set_JQObject
    )
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Field({Static:false, Public:false}, "JQueryObject$JQObject$value", $.Object)
      .Attribute($asm02.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Property({Static:false, Public:true }, "DomRepresentation", $asm03.TypeRef("SharpJS.Dom.Element"));

    $.Property({Static:false, Public:true }, "JQObject", $.Object);


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

JSIL.DeclareNamespace("SharpJS.JSLibraries.JQuery.JQElements");
/* class SharpJS.JSLibraries.JQuery.JQElements.JQDivElement */ 

(function JQDivElement$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm04.SharpJS.JSLibraries.JQuery.JQElement)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm03.SharpJS.Dom.Element)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm02.System.Int32)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(new JSIL.ConstructorSignature($asm03.SharpJS.Dom.Element, [$asm02.System.String]))) ();
  };
  var $S01 = function () {
    return ($S01 = JSIL.Memoize(new JSIL.MethodSignature(null, [$asm02.System.String, "!!0"], ["T"]))) ();
  };


  function JQDivElement__ctor () {
    $T00().prototype._ctor.call(this, $S00().Construct("div"));
    $S01().CallVirtual("Attr$b1", [$asm02.System.Int32], this, "tabIndex", -1);
  }; 

  JSIL.MakeType({
      BaseType: $asm04.TypeRef("SharpJS.JSLibraries.JQuery.JQElement"), 
      Name: "SharpJS.JSLibraries.JQuery.JQElements.JQDivElement", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      JQDivElement__ctor
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

